// This file is auto-generated by @hey-api/openapi-ts

export namespace Brands {
  export type BrandKitReferenceType = 'document' | 'brief' | 'chat';
  export const BrandKitReferenceType = {
    DOCUMENT: 'document',
    BRIEF: 'brief',
    CHAT: 'chat',
  } as const;
  export type BrandKitSectionFieldReferenceType = 'documentChunk' | 'webpage';
  export const BrandKitSectionFieldReferenceType = {
    DOCUMENT_CHUNK: 'documentChunk',
    WEBPAGE: 'webpage',
  } as const;
  export type BrandKitSectionFieldType = 'text' | 'array' | 'richArray';
  export const BrandKitSectionFieldType = {
    TEXT: 'text',
    ARRAY: 'array',
    RICH_ARRAY: 'richArray',
  } as const;
  export type BrandKitStatus = 'draft' | 'inprocess' | 'published' | 'failed';
  export const BrandKitStatus = {
    DRAFT: 'draft',
    INPROCESS: 'inprocess',
    PUBLISHED: 'published',
    FAILED: 'failed',
  } as const;
  export type CreateBrandKitModelRequest = {
    name: string;
    description?: string | null;
    industry?: string | null;
    brandName?: string | null;
    companyName?: string | null;
    logo?: string | null;
  };
  export type CreateBrandKitModelResponse = {
    organizationId: string;
    id: string;
    description?: string | null;
    name: string;
    brandName?: string | null;
    companyName?: string | null;
    logo?: string | null;
    status?: BrandKitStatus | null;
    parentId?: string | null;
    parentType?: ParentTypeEnum | null;
    industry?: string | null;
    tags?: Array<TagList> | null;
    references?: Array<CreateReferenceModelResponse> | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
  };
  export type CreateBrandKitReferenceModelRequest = {
    id: string;
    path: string;
    type: BrandKitReferenceType;
  };
  export type CreateBrandKitSectionFieldModelRequest = {
    name: string;
    type: BrandKitSectionFieldType;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    sources?: Array<string> | null;
    deletable?: boolean | null;
    verified?: boolean | null;
    aiEditable?: boolean | null;
  };
  export type CreateBrandKitSectionFieldModelRequestV2 = {
    name: string;
    type: BrandKitSectionFieldType;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    references?: Array<CreateBrandKitSectionFieldReferenceModelRequest> | null;
    deletable?: boolean | null;
    verified?: boolean | null;
    aiEditable?: boolean | null;
    createdBy?: string | null;
    properties?: {
      [key: string]: unknown;
    } | null;
  };
  export type CreateBrandKitSectionFieldModelResponse = {
    id: string;
    name: string;
    type: BrandKitSectionFieldType;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    sources?: Array<string> | null;
    deletable?: boolean | null;
    verified?: boolean | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    aiEditable?: boolean | null;
  };
  export type CreateBrandKitSectionFieldModelResponseV2 = {
    id: string;
    name: string;
    type: BrandKitSectionFieldType;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    references?: Array<CreateReferenceModelResponse> | null;
    deletable?: boolean | null;
    verified?: boolean | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    aiEditable?: boolean | null;
    properties?: {
      [key: string]: unknown;
    } | null;
  };
  export type CreateBrandKitSectionFieldReferenceModelRequest = {
    id: string;
    path: string;
    type: BrandKitSectionFieldReferenceType;
  };
  export type CreateBrandKitSectionFieldValueEntryModelRequest = {
    name?: string | null;
    tags?: Array<string> | null;
    instructions?: string | null;
    rules?: string | null;
  };
  export type CreateBrandKitSectionFieldValueEntryModelRequestV2 = {
    value: {
      [key: string]: unknown;
    };
  };
  export type CreateBrandKitSectionFieldValueEntryModelResponse = {
    id: string;
    name?: string | null;
    tags?: Array<string> | null;
    instructions?: string | null;
    rules?: string | null;
  };
  export type CreateBrandKitSectionFieldValueEntryModelResponseV2 = {
    id: string;
    [key: string]: unknown | string;
  };
  export type CreateBrandKitSectionModelRequest = {
    deletable?: boolean | null;
    name: string;
    order?: number | null;
    properties?: {
      [key: string]: unknown;
    } | null;
  };
  export type CreateReferenceModelResponse = {
    id: string;
    path: string;
    type: string;
  };
  export type DuplicateError = {
    detail: string;
    loc?: Array<string>;
    msg?: string;
    type?: string;
  };
  export type DuplicateHttpError = {
    detail: Array<DuplicateError>;
  };
  export type GetBrandKitModelResponse = {
    organizationId: string;
    id: string;
    description?: string | null;
    name: string;
    brandName?: string | null;
    companyName?: string | null;
    logo?: string | null;
    status?: string | null;
    parentId?: string | null;
    parentType?: string | null;
    industry?: string | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    tags: Array<TagList> | null;
    references: Array<GetReferenceModelResponse> | null;
    deletedAt?: string | null;
    locked?: boolean | null;
  };
  export type GetBrandKitSectionFieldModelResponse = {
    id: string;
    name: string;
    type: string;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    sources?: Array<string> | null;
    deletable?: boolean | null;
    verified?: boolean | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    aiEditable?: boolean | null;
  };
  export type GetBrandKitSectionFieldModelResponseV2 = {
    id: string;
    name: string;
    type: string;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    references?: Array<GetReferenceModelResponse> | null;
    deletable?: boolean | null;
    verified?: boolean | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    aiEditable?: boolean | null;
    properties?: {
      [key: string]: unknown;
    } | null;
  };
  export type GetBrandKitSectionFieldValueEntryModelResponse = {
    id: string;
    name?: string | null;
    tags?: Array<string> | null;
    instructions?: string | null;
    rules?: string | null;
  };
  export type GetBrandKitSectionFieldValueEntryModelResponseV2 = {
    id: string;
    [key: string]: unknown | string;
  };
  export type GetBrandKitSectionModelResponse = {
    deletable?: boolean | null;
    id: string;
    name: string;
    order?: number | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    properties?: {
      [key: string]: unknown;
    } | null;
  };
  export type GetReferenceModelResponse = {
    id: string;
    path: string;
    type: string;
  };
  export type HttpError = {
    detail: string;
  };
  export type HttpValidationError = {
    detail?: Array<ValidationError>;
  };
  export type ListBrandKitSectionFieldsModelResponse = {
    id: string;
    name: string;
    type: BrandKitSectionFieldType;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    sources?: Array<string> | null;
    deletable?: boolean | null;
    verified?: boolean | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    aiEditable?: boolean | null;
  };
  export type ListBrandKitSectionFieldsModelResponseV2 = {
    id: string;
    name: string;
    type: BrandKitSectionFieldType;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    references?: Array<ListReferencesModelResponseData> | null;
    deletable?: boolean | null;
    verified?: boolean | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    aiEditable?: boolean | null;
    properties?: {
      [key: string]: unknown;
    } | null;
  };
  export type ListBrandKitSectionFieldsModelResponseV3 = {
    totalCount: number;
    pageNumber: number;
    pageSize: number;
    data: Array<ModelsV3ListBrandKitSectionFieldsModelV3DataList>;
  };
  export type ListBrandKitSectionsModelResponse = {
    deletable?: boolean | null;
    id: string;
    name: string;
    order?: number | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    deletedAt?: string | null;
    properties?: {
      [key: string]: unknown;
    } | null;
  };
  export type ListBrandKitsModelResponse = {
    totalCount: number;
    pageSize: number;
    pageNumber: number;
    data: Array<AppModelsV1ListBrandKitsModelDataList>;
  };
  export type ListReferencesModelResponse = {
    totalCount: number;
    pageSize: number;
    pageNumber: number;
    data: Array<ListReferencesModelResponseData>;
  };
  export type ListReferencesModelResponseData = {
    id: string;
    path: string;
    type: string;
  };
  export type ParentTypeEnum = 'brandkit' | '';
  export const ParentTypeEnum = {
    BRANDKIT: 'brandkit',
    '': '',
  } as const;
  export type SortByEnum = 'createdOn' | 'updatedOn';
  export const SortByEnum = {
    CREATED_ON: 'createdOn',
    UPDATED_ON: 'updatedOn',
  } as const;
  export type SortTypeEnum = 'asc' | 'desc';
  export const SortTypeEnum = {
    ASC: 'asc',
    DESC: 'desc',
  } as const;
  export type TagList = {
    category: string;
    values: Array<string>;
  };
  export type UpdateBrandKitModelRequest = {
    status?: BrandKitStatus | null;
    name?: string | null;
    description?: string | null;
    parentId?: string | null;
    parentType?: ParentTypeEnum | null;
    industry?: string | null;
    tags?: Array<TagList> | null;
    brandName?: string | null;
    companyName?: string | null;
    logo?: string | null;
    locked?: boolean | null;
  };
  export type UpdateBrandKitSectionFieldModelRequest = {
    deletable?: boolean | null;
    name?: string | null;
    verified?: boolean | null;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    sources?: Array<string> | null;
    aiEditable?: boolean | null;
  };
  export type UpdateBrandKitSectionFieldModelRequestV2 = {
    deletable?: boolean | null;
    name?: string | null;
    verified?: boolean | null;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    sources?: Array<string> | null;
    aiEditable?: boolean | null;
    updatedBy?: string | null;
    properties?: {
      [key: string]: unknown;
    } | null;
  };
  export type UpdateBrandKitSectionFieldModelResponse = {
    id: string;
    name: string;
    type: BrandKitSectionFieldType;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    sources?: Array<string> | null;
    deletable?: boolean | null;
    verified?: boolean | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    aiEditable?: boolean | null;
  };
  export type UpdateBrandKitSectionFieldModelResponseV2 = {
    id: string;
    name: string;
    type: BrandKitSectionFieldType;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    deletable?: boolean | null;
    verified?: boolean | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    aiEditable?: boolean | null;
    references: Array<GetReferenceModelResponse> | null;
    properties?: {
      [key: string]: unknown;
    } | null;
  };
  export type UpdateBrandKitSectionFieldValueEntryModelRequest = {
    name?: string | null;
    tags?: Array<string> | null;
    instructions?: string | null;
    rules?: string | null;
  };
  export type UpdateBrandKitSectionFieldValueEntryModelRequestV2 = {
    value: {
      [key: string]: unknown;
    };
  };
  export type UpdateBrandKitSectionFieldValueEntryModelResponse = {
    id: string;
    name?: string | null;
    tags?: Array<string> | null;
    instructions?: string | null;
    rules?: string | null;
  };
  export type UpdateBrandKitSectionFieldValueEntryModelResponseV2 = {
    id: string;
    [key: string]: unknown | string;
  };
  export type UpdateBrandKitSectionModelRequest = {
    deletable?: boolean | null;
    order?: number | null;
    name?: string | null;
    properties?: {
      [key: string]: unknown;
    } | null;
  };
  export type UpdateBrandKitSectionModelResponse = {
    deletable?: boolean | null;
    id: string;
    name: string;
    order?: number | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    properties?: {
      [key: string]: unknown;
    } | null;
  };
  export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
      [key: string]: unknown;
    };
  };
  export type AppModelsV1ListBrandKitsModelDataList = {
    organizationId: string;
    id: string;
    description?: string | null;
    name: string;
    brandName?: string | null;
    companyName?: string | null;
    logo?: string | null;
    status?: string | null;
    parentId?: string | null;
    parentType?: string | null;
    industry?: string | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    tags?: Array<TagList> | null;
    references?: Array<ListReferencesModelResponseData> | null;
    deletedAt?: string | null;
  };
  export type ModelsV3ListBrandKitSectionFieldsModelV3DataList = {
    id: string;
    name: string;
    type: BrandKitSectionFieldType;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    references?: Array<ListReferencesModelResponseData> | null;
    deletable?: boolean | null;
    verified?: boolean | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    aiEditable?: boolean | null;
    properties?: {
      [key: string]: unknown;
    } | null;
  };
  export type GetVersionData = {
    body?: never;
    path?: never;
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/version';
  };
  export type GetVersionResponses = {
    /**
     * Successful Response
     */
    200: unknown;
  };
  export type ListBrandKitSectionsAdminData = {
    body?: never;
    headers: {
      'x-sc-src-tenant-id': string;
      'x-sc-ai-tenant-id'?: string;
      'x-sc-src-user-id'?: string;
    };
    path: {
      brandkitId: string;
    };
    query?: {
      sectionIds?: Array<string> | null;
      includeDeleted?: boolean | null;
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/admin/v1/brandkits/{brandkitId}/sections';
  };
  export type ListBrandKitSectionsAdminErrors = {
    /**
     * Resource not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Brandkit operation failed
     */
    500: HttpError;
  };
  export type ListBrandKitSectionsAdminError =
    ListBrandKitSectionsAdminErrors[keyof ListBrandKitSectionsAdminErrors];
  export type ListBrandKitSectionsAdminResponses = {
    /**
     * Successful Response
     */
    200: Array<ListBrandKitSectionsModelResponse>;
  };
  export type ListBrandKitSectionsAdminResponse =
    ListBrandKitSectionsAdminResponses[keyof ListBrandKitSectionsAdminResponses];
  export type GetBrandKitSectionAdminData = {
    body?: never;
    headers: {
      'x-sc-src-tenant-id': string;
      'x-sc-ai-tenant-id'?: string;
      'x-sc-src-user-id'?: string;
    };
    path: {
      brandkitId: string;
      sectionId: string;
    };
    query?: {
      includeDeleted?: boolean | null;
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/admin/v1/brandkits/{brandkitId}/sections/{sectionId}';
  };
  export type GetBrandKitSectionAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type GetBrandKitSectionAdminError =
    GetBrandKitSectionAdminErrors[keyof GetBrandKitSectionAdminErrors];
  export type GetBrandKitSectionAdminResponses = {
    /**
     * Successful Response
     */
    200: GetBrandKitSectionModelResponse;
  };
  export type GetBrandKitSectionAdminResponse =
    GetBrandKitSectionAdminResponses[keyof GetBrandKitSectionAdminResponses];
  export type ListBrandKitSectionFieldsData = {
    body?: never;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields';
  };
  export type ListBrandKitSectionFieldsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type ListBrandKitSectionFieldsError =
    ListBrandKitSectionFieldsErrors[keyof ListBrandKitSectionFieldsErrors];
  export type ListBrandKitSectionFieldsResponses = {
    /**
     * Successful Response
     */
    200: Array<ListBrandKitSectionFieldsModelResponseV2>;
  };
  export type ListBrandKitSectionFieldsResponse =
    ListBrandKitSectionFieldsResponses[keyof ListBrandKitSectionFieldsResponses];
  export type CreateBrandKitSectionFieldData = {
    body: CreateBrandKitSectionFieldModelRequestV2;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields';
  };
  export type CreateBrandKitSectionFieldErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type CreateBrandKitSectionFieldError =
    CreateBrandKitSectionFieldErrors[keyof CreateBrandKitSectionFieldErrors];
  export type CreateBrandKitSectionFieldResponses = {
    /**
     * Successful Response
     */
    201: CreateBrandKitSectionFieldModelResponseV2;
  };
  export type CreateBrandKitSectionFieldResponse =
    CreateBrandKitSectionFieldResponses[keyof CreateBrandKitSectionFieldResponses];
  export type ListBrandKitSectionFieldsV3Data = {
    body?: never;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
    };
    query?: {
      pageNumber?: number;
      pageSize?: number;
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v3/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields';
  };
  export type ListBrandKitSectionFieldsV3Errors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type ListBrandKitSectionFieldsV3Error =
    ListBrandKitSectionFieldsV3Errors[keyof ListBrandKitSectionFieldsV3Errors];
  export type ListBrandKitSectionFieldsV3Responses = {
    /**
     * Successful Response
     */
    200: ListBrandKitSectionFieldsModelResponseV3;
  };
  export type ListBrandKitSectionFieldsV3Response =
    ListBrandKitSectionFieldsV3Responses[keyof ListBrandKitSectionFieldsV3Responses];
  export type ListBrandKitSectionFieldsAdminData = {
    body?: never;
    headers: {
      'x-sc-src-tenant-id': string;
      'x-sc-ai-tenant-id'?: string;
      'x-sc-src-user-id'?: string;
    };
    path: {
      brandkitId: string;
      sectionId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/admin/v1/brandkits/{brandkitId}/sections/{sectionId}/fields';
  };
  export type ListBrandKitSectionFieldsAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type ListBrandKitSectionFieldsAdminError =
    ListBrandKitSectionFieldsAdminErrors[keyof ListBrandKitSectionFieldsAdminErrors];
  export type ListBrandKitSectionFieldsAdminResponses = {
    /**
     * Successful Response
     */
    200: Array<ListBrandKitSectionFieldsModelResponseV2>;
  };
  export type ListBrandKitSectionFieldsAdminResponse =
    ListBrandKitSectionFieldsAdminResponses[keyof ListBrandKitSectionFieldsAdminResponses];
  export type GetBrandKitSectionFieldAdminData = {
    body?: never;
    headers: {
      'x-sc-src-tenant-id': string;
      'x-sc-ai-tenant-id'?: string;
      'x-sc-src-user-id'?: string;
    };
    path: {
      brandkitId: string;
      sectionId: string;
      fieldId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/admin/v1/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}';
  };
  export type GetBrandKitSectionFieldAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type GetBrandKitSectionFieldAdminError =
    GetBrandKitSectionFieldAdminErrors[keyof GetBrandKitSectionFieldAdminErrors];
  export type GetBrandKitSectionFieldAdminResponses = {
    /**
     * Successful Response
     */
    200: GetBrandKitSectionFieldModelResponseV2;
  };
  export type GetBrandKitSectionFieldAdminResponse =
    GetBrandKitSectionFieldAdminResponses[keyof GetBrandKitSectionFieldAdminResponses];
  export type GetBrandKitSectionFieldData = {
    body?: never;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
      fieldId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}';
  };
  export type GetBrandKitSectionFieldErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type GetBrandKitSectionFieldError =
    GetBrandKitSectionFieldErrors[keyof GetBrandKitSectionFieldErrors];
  export type GetBrandKitSectionFieldResponses = {
    /**
     * Successful Response
     */
    200: GetBrandKitSectionFieldModelResponseV2;
  };
  export type GetBrandKitSectionFieldResponse =
    GetBrandKitSectionFieldResponses[keyof GetBrandKitSectionFieldResponses];
  export type UpdateBrandKitSectionFieldData = {
    body: UpdateBrandKitSectionFieldModelRequestV2;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
      fieldId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}';
  };
  export type UpdateBrandKitSectionFieldErrors = {
    /**
     * Invalid parameters
     */
    400: HttpError;
    /**
     * Resource not found
     */
    404: HttpError;
    /**
     * Brand Kit is locked
     */
    409: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Brandkit operation failed
     */
    500: HttpError;
  };
  export type UpdateBrandKitSectionFieldError =
    UpdateBrandKitSectionFieldErrors[keyof UpdateBrandKitSectionFieldErrors];
  export type UpdateBrandKitSectionFieldResponses = {
    /**
     * Successful Response
     */
    200: UpdateBrandKitSectionFieldModelResponseV2;
  };
  export type UpdateBrandKitSectionFieldResponse =
    UpdateBrandKitSectionFieldResponses[keyof UpdateBrandKitSectionFieldResponses];
  export type CreateBrandKitSectionFieldValueEntryV2Data = {
    body: CreateBrandKitSectionFieldValueEntryModelRequestV2;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
      fieldId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/values';
  };
  export type CreateBrandKitSectionFieldValueEntryV2Errors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type CreateBrandKitSectionFieldValueEntryV2Error =
    CreateBrandKitSectionFieldValueEntryV2Errors[keyof CreateBrandKitSectionFieldValueEntryV2Errors];
  export type CreateBrandKitSectionFieldValueEntryV2Responses = {
    /**
     * Successful Response
     */
    201: CreateBrandKitSectionFieldValueEntryModelResponseV2;
  };
  export type CreateBrandKitSectionFieldValueEntryV2Response =
    CreateBrandKitSectionFieldValueEntryV2Responses[keyof CreateBrandKitSectionFieldValueEntryV2Responses];
  export type GetBrandKitSectionFieldValueEntryV2Data = {
    body?: never;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
      fieldId: string;
      valueEntryId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/values/{valueEntryId}';
  };
  export type GetBrandKitSectionFieldValueEntryV2Errors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type GetBrandKitSectionFieldValueEntryV2Error =
    GetBrandKitSectionFieldValueEntryV2Errors[keyof GetBrandKitSectionFieldValueEntryV2Errors];
  export type GetBrandKitSectionFieldValueEntryV2Responses = {
    /**
     * Successful Response
     */
    200: GetBrandKitSectionFieldValueEntryModelResponseV2;
  };
  export type GetBrandKitSectionFieldValueEntryV2Response =
    GetBrandKitSectionFieldValueEntryV2Responses[keyof GetBrandKitSectionFieldValueEntryV2Responses];
  export type UpdateBrandKitSectionFieldValueEntryV2Data = {
    body: UpdateBrandKitSectionFieldValueEntryModelRequestV2;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
      fieldId: string;
      valueEntryId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/values/{valueEntryId}';
  };
  export type UpdateBrandKitSectionFieldValueEntryV2Errors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type UpdateBrandKitSectionFieldValueEntryV2Error =
    UpdateBrandKitSectionFieldValueEntryV2Errors[keyof UpdateBrandKitSectionFieldValueEntryV2Errors];
  export type UpdateBrandKitSectionFieldValueEntryV2Responses = {
    /**
     * Successful Response
     */
    200: UpdateBrandKitSectionFieldValueEntryModelResponseV2;
  };
  export type UpdateBrandKitSectionFieldValueEntryV2Response =
    UpdateBrandKitSectionFieldValueEntryV2Responses[keyof UpdateBrandKitSectionFieldValueEntryV2Responses];
  export type GetPublicOpenapiData = {
    body?: never;
    path?: never;
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/docs/openapi.json';
  };
  export type GetPublicOpenapiResponses = {
    /**
     * Successful Response
     */
    200: unknown;
  };
  export type GetPublicSwaggerUiData = {
    body?: never;
    path?: never;
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/docs';
  };
  export type GetPublicSwaggerUiResponses = {
    /**
     * Successful Response
     */
    200: string;
  };
  export type GetPublicSwaggerUiResponse =
    GetPublicSwaggerUiResponses[keyof GetPublicSwaggerUiResponses];
  export type GetPublicRedocUiData = {
    body?: never;
    path?: never;
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/docs/redoc';
  };
  export type GetPublicRedocUiResponses = {
    /**
     * Successful Response
     */
    200: string;
  };
  export type GetPublicRedocUiResponse = GetPublicRedocUiResponses[keyof GetPublicRedocUiResponses];
  export type ClientOptions = {
    baseUrl: 'https://example.com/ai-brands-api' | (string & {});
  };
}
