// This file is auto-generated by @hey-api/openapi-ts

export namespace Brands {
  export type BrandKitReferenceType = 'document' | 'brief' | 'chat';
  export const BrandKitReferenceType = {
    DOCUMENT: 'document',
    BRIEF: 'brief',
    CHAT: 'chat',
  } as const;
  export type BrandKitSectionFieldReferenceType = 'documentChunk' | 'webpage';
  export const BrandKitSectionFieldReferenceType = {
    DOCUMENT_CHUNK: 'documentChunk',
    WEBPAGE: 'webpage',
  } as const;
  export type BrandKitSectionFieldType = 'text' | 'array' | 'richArray';
  export const BrandKitSectionFieldType = {
    TEXT: 'text',
    ARRAY: 'array',
    RICH_ARRAY: 'richArray',
  } as const;
  export type BrandKitStatus = 'draft' | 'inprocess' | 'published' | 'failed';
  export const BrandKitStatus = {
    DRAFT: 'draft',
    INPROCESS: 'inprocess',
    PUBLISHED: 'published',
    FAILED: 'failed',
  } as const;
  export type CreateBrandKitModelRequest = {
    name: string;
    description?: string | null;
    industry?: string | null;
    brandName?: string | null;
    companyName?: string | null;
    logo?: string | null;
  };
  export type CreateBrandKitModelResponse = {
    organizationId: string;
    id: string;
    description?: string | null;
    name: string;
    brandName?: string | null;
    companyName?: string | null;
    logo?: string | null;
    status?: BrandKitStatus | null;
    parentId?: string | null;
    parentType?: ParentTypeEnum | null;
    industry?: string | null;
    tags?: Array<TagList> | null;
    references?: Array<CreateReferenceModelResponse> | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
  };
  export type CreateBrandKitReferenceModelRequest = {
    id: string;
    path: string;
    type: BrandKitReferenceType;
  };
  export type CreateBrandKitSectionFieldModelRequest = {
    name: string;
    type: BrandKitSectionFieldType;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    sources?: Array<string> | null;
    deletable?: boolean | null;
    verified?: boolean | null;
    aiEditable?: boolean | null;
  };
  export type CreateBrandKitSectionFieldModelRequestV2 = {
    name: string;
    type: BrandKitSectionFieldType;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    references?: Array<CreateBrandKitSectionFieldReferenceModelRequest> | null;
    deletable?: boolean | null;
    verified?: boolean | null;
    aiEditable?: boolean | null;
    createdBy?: string | null;
    properties?: {
      [key: string]: unknown;
    } | null;
  };
  export type CreateBrandKitSectionFieldModelResponse = {
    id: string;
    name: string;
    type: BrandKitSectionFieldType;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    sources?: Array<string> | null;
    deletable?: boolean | null;
    verified?: boolean | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    aiEditable?: boolean | null;
  };
  export type CreateBrandKitSectionFieldModelResponseV2 = {
    id: string;
    name: string;
    type: BrandKitSectionFieldType;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    references?: Array<CreateReferenceModelResponse> | null;
    deletable?: boolean | null;
    verified?: boolean | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    aiEditable?: boolean | null;
    properties?: {
      [key: string]: unknown;
    } | null;
  };
  export type CreateBrandKitSectionFieldReferenceModelRequest = {
    id: string;
    path: string;
    type: BrandKitSectionFieldReferenceType;
  };
  export type CreateBrandKitSectionFieldValueEntryModelRequest = {
    name?: string | null;
    tags?: Array<string> | null;
    instructions?: string | null;
    rules?: string | null;
  };
  export type CreateBrandKitSectionFieldValueEntryModelRequestV2 = {
    value: {
      [key: string]: unknown;
    };
  };
  export type CreateBrandKitSectionFieldValueEntryModelResponse = {
    id: string;
    name?: string | null;
    tags?: Array<string> | null;
    instructions?: string | null;
    rules?: string | null;
  };
  export type CreateBrandKitSectionFieldValueEntryModelResponseV2 = {
    id: string;
    [key: string]: unknown | string;
  };
  export type CreateBrandKitSectionModelRequest = {
    deletable?: boolean | null;
    name: string;
    order?: number | null;
    properties?: {
      [key: string]: unknown;
    } | null;
  };
  export type CreateReferenceModelResponse = {
    id: string;
    path: string;
    type: string;
  };
  export type DuplicateError = {
    detail: string;
    loc?: Array<string>;
    msg?: string;
    type?: string;
  };
  export type DuplicateHttpError = {
    detail: Array<DuplicateError>;
  };
  export type GetBrandKitModelResponse = {
    organizationId: string;
    id: string;
    description?: string | null;
    name: string;
    brandName?: string | null;
    companyName?: string | null;
    logo?: string | null;
    status?: string | null;
    parentId?: string | null;
    parentType?: string | null;
    industry?: string | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    tags: Array<TagList> | null;
    references: Array<GetReferenceModelResponse> | null;
    deletedAt?: string | null;
    locked?: boolean | null;
  };
  export type GetBrandKitSectionFieldModelResponse = {
    id: string;
    name: string;
    type: string;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    sources?: Array<string> | null;
    deletable?: boolean | null;
    verified?: boolean | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    aiEditable?: boolean | null;
  };
  export type GetBrandKitSectionFieldModelResponseV2 = {
    id: string;
    name: string;
    type: string;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    references?: Array<GetReferenceModelResponse> | null;
    deletable?: boolean | null;
    verified?: boolean | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    aiEditable?: boolean | null;
    properties?: {
      [key: string]: unknown;
    } | null;
  };
  export type GetBrandKitSectionFieldValueEntryModelResponse = {
    id: string;
    name?: string | null;
    tags?: Array<string> | null;
    instructions?: string | null;
    rules?: string | null;
  };
  export type GetBrandKitSectionFieldValueEntryModelResponseV2 = {
    id: string;
    [key: string]: unknown | string;
  };
  export type GetBrandKitSectionModelResponse = {
    deletable?: boolean | null;
    id: string;
    name: string;
    order?: number | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    properties?: {
      [key: string]: unknown;
    } | null;
  };
  export type GetReferenceModelResponse = {
    id: string;
    path: string;
    type: string;
  };
  export type HttpError = {
    detail: string;
  };
  export type HttpValidationError = {
    detail?: Array<ValidationError>;
  };
  export type ListBrandKitSectionFieldsModelResponse = {
    id: string;
    name: string;
    type: BrandKitSectionFieldType;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    sources?: Array<string> | null;
    deletable?: boolean | null;
    verified?: boolean | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    aiEditable?: boolean | null;
  };
  export type ListBrandKitSectionFieldsModelResponseV2 = {
    id: string;
    name: string;
    type: BrandKitSectionFieldType;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    references?: Array<ListReferencesModelResponseData> | null;
    deletable?: boolean | null;
    verified?: boolean | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    aiEditable?: boolean | null;
    properties?: {
      [key: string]: unknown;
    } | null;
  };
  export type ListBrandKitSectionFieldsModelResponseV3 = {
    totalCount: number;
    pageNumber: number;
    pageSize: number;
    data: Array<ModelsV3ListBrandKitSectionFieldsModelV3DataList>;
  };
  export type ListBrandKitSectionsModelResponse = {
    deletable?: boolean | null;
    id: string;
    name: string;
    order?: number | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    deletedAt?: string | null;
    properties?: {
      [key: string]: unknown;
    } | null;
  };
  export type ListBrandKitsModelResponse = {
    totalCount: number;
    pageSize: number;
    pageNumber: number;
    data: Array<AppModelsV1ListBrandKitsModelDataList>;
  };
  export type ListReferencesModelResponse = {
    totalCount: number;
    pageSize: number;
    pageNumber: number;
    data: Array<ListReferencesModelResponseData>;
  };
  export type ListReferencesModelResponseData = {
    id: string;
    path: string;
    type: string;
  };
  export type ParentTypeEnum = 'brandkit' | '';
  export const ParentTypeEnum = {
    BRANDKIT: 'brandkit',
    '': '',
  } as const;
  export type SortByEnum = 'createdOn' | 'updatedOn';
  export const SortByEnum = {
    CREATED_ON: 'createdOn',
    UPDATED_ON: 'updatedOn',
  } as const;
  export type SortTypeEnum = 'asc' | 'desc';
  export const SortTypeEnum = {
    ASC: 'asc',
    DESC: 'desc',
  } as const;
  export type TagList = {
    category: string;
    values: Array<string>;
  };
  export type UpdateBrandKitModelRequest = {
    status?: BrandKitStatus | null;
    name?: string | null;
    description?: string | null;
    parentId?: string | null;
    parentType?: ParentTypeEnum | null;
    industry?: string | null;
    tags?: Array<TagList> | null;
    brandName?: string | null;
    companyName?: string | null;
    logo?: string | null;
    locked?: boolean | null;
  };
  export type UpdateBrandKitSectionFieldModelRequest = {
    deletable?: boolean | null;
    name?: string | null;
    verified?: boolean | null;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    sources?: Array<string> | null;
    aiEditable?: boolean | null;
  };
  export type UpdateBrandKitSectionFieldModelRequestV2 = {
    deletable?: boolean | null;
    name?: string | null;
    verified?: boolean | null;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    sources?: Array<string> | null;
    aiEditable?: boolean | null;
    updatedBy?: string | null;
    properties?: {
      [key: string]: unknown;
    } | null;
  };
  export type UpdateBrandKitSectionFieldModelResponse = {
    id: string;
    name: string;
    type: BrandKitSectionFieldType;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    sources?: Array<string> | null;
    deletable?: boolean | null;
    verified?: boolean | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    aiEditable?: boolean | null;
  };
  export type UpdateBrandKitSectionFieldModelResponseV2 = {
    id: string;
    name: string;
    type: BrandKitSectionFieldType;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    deletable?: boolean | null;
    verified?: boolean | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    aiEditable?: boolean | null;
    references: Array<GetReferenceModelResponse> | null;
    properties?: {
      [key: string]: unknown;
    } | null;
  };
  export type UpdateBrandKitSectionFieldValueEntryModelRequest = {
    name?: string | null;
    tags?: Array<string> | null;
    instructions?: string | null;
    rules?: string | null;
  };
  export type UpdateBrandKitSectionFieldValueEntryModelRequestV2 = {
    value: {
      [key: string]: unknown;
    };
  };
  export type UpdateBrandKitSectionFieldValueEntryModelResponse = {
    id: string;
    name?: string | null;
    tags?: Array<string> | null;
    instructions?: string | null;
    rules?: string | null;
  };
  export type UpdateBrandKitSectionFieldValueEntryModelResponseV2 = {
    id: string;
    [key: string]: unknown | string;
  };
  export type UpdateBrandKitSectionModelRequest = {
    deletable?: boolean | null;
    order?: number | null;
    name?: string | null;
    properties?: {
      [key: string]: unknown;
    } | null;
  };
  export type UpdateBrandKitSectionModelResponse = {
    deletable?: boolean | null;
    id: string;
    name: string;
    order?: number | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    properties?: {
      [key: string]: unknown;
    } | null;
  };
  export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
      [key: string]: unknown;
    };
  };
  export type AppModelsV1ListBrandKitsModelDataList = {
    organizationId: string;
    id: string;
    description?: string | null;
    name: string;
    brandName?: string | null;
    companyName?: string | null;
    logo?: string | null;
    status?: string | null;
    parentId?: string | null;
    parentType?: string | null;
    industry?: string | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    tags?: Array<TagList> | null;
    references?: Array<ListReferencesModelResponseData> | null;
    deletedAt?: string | null;
  };
  export type ModelsV3ListBrandKitSectionFieldsModelV3DataList = {
    id: string;
    name: string;
    type: BrandKitSectionFieldType;
    order?: number | null;
    value?:
      | string
      | {
          [key: string]: unknown;
        }
      | Array<unknown>
      | null;
    intent?: string | null;
    references?: Array<ListReferencesModelResponseData> | null;
    deletable?: boolean | null;
    verified?: boolean | null;
    createdOn?: string | null;
    createdBy?: string | null;
    updatedOn?: string | null;
    updatedBy?: string | null;
    aiEditable?: boolean | null;
    properties?: {
      [key: string]: unknown;
    } | null;
  };
  export type GetVersionData = {
    body?: never;
    path?: never;
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/version';
  };
  export type GetVersionResponses = {
    /**
     * Successful Response
     */
    200: unknown;
  };
  export type ListBrandKitsData = {
    body?: never;
    path: {
      organizationId: string;
    };
    query?: {
      pageNumber?: number;
      pageSize?: number;
      parentId?: string | null;
      status?: string | null;
      search?: string | null;
      referenceType?: string | null;
      referenceId?: string | null;
      includeDeleted?: boolean | null;
      brandkitIds?: Array<string> | null;
      sortBy?: SortByEnum;
      sortType?: SortTypeEnum;
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits';
  };
  export type ListBrandKitsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type ListBrandKitsError = ListBrandKitsErrors[keyof ListBrandKitsErrors];
  export type ListBrandKitsResponses = {
    /**
     * Successful Response
     */
    200: ListBrandKitsModelResponse;
  };
  export type ListBrandKitsResponse = ListBrandKitsResponses[keyof ListBrandKitsResponses];
  export type CreateBrandKitData = {
    body: CreateBrandKitModelRequest;
    path: {
      organizationId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits';
  };
  export type CreateBrandKitErrors = {
    /**
     * Duplicate brandkit name
     */
    400: DuplicateHttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Brandkit operation failed
     */
    500: HttpError;
  };
  export type CreateBrandKitError = CreateBrandKitErrors[keyof CreateBrandKitErrors];
  export type CreateBrandKitResponses = {
    /**
     * Successful Response
     */
    201: CreateBrandKitModelResponse;
  };
  export type CreateBrandKitResponse = CreateBrandKitResponses[keyof CreateBrandKitResponses];
  export type DeleteBrandKitData = {
    body?: never;
    path: {
      organizationId: string;
      brandkitId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}';
  };
  export type DeleteBrandKitErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type DeleteBrandKitError = DeleteBrandKitErrors[keyof DeleteBrandKitErrors];
  export type DeleteBrandKitResponses = {
    /**
     * Successful Response
     */
    204: void;
  };
  export type DeleteBrandKitResponse = DeleteBrandKitResponses[keyof DeleteBrandKitResponses];
  export type GetBrandKitData = {
    body?: never;
    path: {
      organizationId: string;
      brandkitId: string;
    };
    query?: {
      includeDeleted?: boolean | null;
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}';
  };
  export type GetBrandKitErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type GetBrandKitError = GetBrandKitErrors[keyof GetBrandKitErrors];
  export type GetBrandKitResponses = {
    /**
     * Successful Response
     */
    200: GetBrandKitModelResponse;
  };
  export type GetBrandKitResponse = GetBrandKitResponses[keyof GetBrandKitResponses];
  export type UpdateBrandKitData = {
    body: UpdateBrandKitModelRequest;
    path: {
      organizationId: string;
      brandkitId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}';
  };
  export type UpdateBrandKitErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type UpdateBrandKitError = UpdateBrandKitErrors[keyof UpdateBrandKitErrors];
  export type UpdateBrandKitResponses = {
    /**
     * Successful Response
     */
    200: unknown;
  };
  export type ListBrandKitReferencesData = {
    body?: never;
    path: {
      organizationId: string;
      brandkitId: string;
    };
    query?: {
      type?: string | null;
      pageNumber?: number;
      pageSize?: number;
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/references';
  };
  export type ListBrandKitReferencesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type ListBrandKitReferencesError =
    ListBrandKitReferencesErrors[keyof ListBrandKitReferencesErrors];
  export type ListBrandKitReferencesResponses = {
    /**
     * Successful Response
     */
    200: ListReferencesModelResponse;
  };
  export type ListBrandKitReferencesResponse =
    ListBrandKitReferencesResponses[keyof ListBrandKitReferencesResponses];
  export type CreateBrandKitReferenceData = {
    body: CreateBrandKitReferenceModelRequest;
    path: {
      organizationId: string;
      brandkitId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/references';
  };
  export type CreateBrandKitReferenceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type CreateBrandKitReferenceError =
    CreateBrandKitReferenceErrors[keyof CreateBrandKitReferenceErrors];
  export type CreateBrandKitReferenceResponses = {
    /**
     * Successful Response
     */
    201: unknown;
  };
  export type DeleteBrandKitReferenceData = {
    body?: never;
    path: {
      organizationId: string;
      brandkitId: string;
      referenceId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/references/{referenceId}';
  };
  export type DeleteBrandKitReferenceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type DeleteBrandKitReferenceError =
    DeleteBrandKitReferenceErrors[keyof DeleteBrandKitReferenceErrors];
  export type DeleteBrandKitReferenceResponses = {
    /**
     * Successful Response
     */
    204: void;
  };
  export type DeleteBrandKitReferenceResponse =
    DeleteBrandKitReferenceResponses[keyof DeleteBrandKitReferenceResponses];
  export type GetBrandKitReferenceData = {
    body?: never;
    path: {
      organizationId: string;
      brandkitId: string;
      referenceId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/references/{referenceId}';
  };
  export type GetBrandKitReferenceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type GetBrandKitReferenceError =
    GetBrandKitReferenceErrors[keyof GetBrandKitReferenceErrors];
  export type GetBrandKitReferenceResponses = {
    /**
     * Successful Response
     */
    200: GetReferenceModelResponse;
  };
  export type GetBrandKitReferenceResponse =
    GetBrandKitReferenceResponses[keyof GetBrandKitReferenceResponses];
  export type ListBrandKitSectionsData = {
    body?: never;
    path: {
      organizationId: string;
      brandkitId: string;
    };
    query?: {
      sectionIds?: Array<string> | null;
      includeDeleted?: boolean | null;
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections';
  };
  export type ListBrandKitSectionsErrors = {
    /**
     * Resource not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Brandkit operation failed
     */
    500: HttpError;
  };
  export type ListBrandKitSectionsError =
    ListBrandKitSectionsErrors[keyof ListBrandKitSectionsErrors];
  export type ListBrandKitSectionsResponses = {
    /**
     * Successful Response
     */
    200: Array<ListBrandKitSectionsModelResponse>;
  };
  export type ListBrandKitSectionsResponse =
    ListBrandKitSectionsResponses[keyof ListBrandKitSectionsResponses];
  export type CreateBrandKitSectionData = {
    body: CreateBrandKitSectionModelRequest;
    path: {
      organizationId: string;
      brandkitId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections';
  };
  export type CreateBrandKitSectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type CreateBrandKitSectionError =
    CreateBrandKitSectionErrors[keyof CreateBrandKitSectionErrors];
  export type CreateBrandKitSectionResponses = {
    /**
     * Successful Response
     */
    201: unknown;
  };
  export type ListBrandKitSectionsAdminData = {
    body?: never;
    headers: {
      'x-sc-src-tenant-id': string;
      'x-sc-ai-tenant-id'?: string;
      'x-sc-src-user-id'?: string;
    };
    path: {
      brandkitId: string;
    };
    query?: {
      sectionIds?: Array<string> | null;
      includeDeleted?: boolean | null;
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/admin/v1/brandkits/{brandkitId}/sections';
  };
  export type ListBrandKitSectionsAdminErrors = {
    /**
     * Resource not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Brandkit operation failed
     */
    500: HttpError;
  };
  export type ListBrandKitSectionsAdminError =
    ListBrandKitSectionsAdminErrors[keyof ListBrandKitSectionsAdminErrors];
  export type ListBrandKitSectionsAdminResponses = {
    /**
     * Successful Response
     */
    200: Array<ListBrandKitSectionsModelResponse>;
  };
  export type ListBrandKitSectionsAdminResponse =
    ListBrandKitSectionsAdminResponses[keyof ListBrandKitSectionsAdminResponses];
  export type DeleteBrandKitSectionData = {
    body?: never;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}';
  };
  export type DeleteBrandKitSectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type DeleteBrandKitSectionError =
    DeleteBrandKitSectionErrors[keyof DeleteBrandKitSectionErrors];
  export type DeleteBrandKitSectionResponses = {
    /**
     * Successful Response
     */
    204: void;
  };
  export type DeleteBrandKitSectionResponse =
    DeleteBrandKitSectionResponses[keyof DeleteBrandKitSectionResponses];
  export type GetBrandKitSectionData = {
    body?: never;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
    };
    query?: {
      includeDeleted?: boolean | null;
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}';
  };
  export type GetBrandKitSectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type GetBrandKitSectionError = GetBrandKitSectionErrors[keyof GetBrandKitSectionErrors];
  export type GetBrandKitSectionResponses = {
    /**
     * Successful Response
     */
    200: GetBrandKitSectionModelResponse;
  };
  export type GetBrandKitSectionResponse =
    GetBrandKitSectionResponses[keyof GetBrandKitSectionResponses];
  export type UpdateBrandKitSectionData = {
    body: UpdateBrandKitSectionModelRequest;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}';
  };
  export type UpdateBrandKitSectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type UpdateBrandKitSectionError =
    UpdateBrandKitSectionErrors[keyof UpdateBrandKitSectionErrors];
  export type UpdateBrandKitSectionResponses = {
    /**
     * Successful Response
     */
    200: UpdateBrandKitSectionModelResponse;
  };
  export type UpdateBrandKitSectionResponse =
    UpdateBrandKitSectionResponses[keyof UpdateBrandKitSectionResponses];
  export type GetBrandKitSectionAdminData = {
    body?: never;
    headers: {
      'x-sc-src-tenant-id': string;
      'x-sc-ai-tenant-id'?: string;
      'x-sc-src-user-id'?: string;
    };
    path: {
      brandkitId: string;
      sectionId: string;
    };
    query?: {
      includeDeleted?: boolean | null;
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/admin/v1/brandkits/{brandkitId}/sections/{sectionId}';
  };
  export type GetBrandKitSectionAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type GetBrandKitSectionAdminError =
    GetBrandKitSectionAdminErrors[keyof GetBrandKitSectionAdminErrors];
  export type GetBrandKitSectionAdminResponses = {
    /**
     * Successful Response
     */
    200: GetBrandKitSectionModelResponse;
  };
  export type GetBrandKitSectionAdminResponse =
    GetBrandKitSectionAdminResponses[keyof GetBrandKitSectionAdminResponses];
  export type ListBrandKitSectionFieldsLegacyData = {
    body?: never;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields';
  };
  export type ListBrandKitSectionFieldsLegacyErrors = {
    /**
     * Resource not found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Brandkit operation failed
     */
    500: HttpError;
  };
  export type ListBrandKitSectionFieldsLegacyError =
    ListBrandKitSectionFieldsLegacyErrors[keyof ListBrandKitSectionFieldsLegacyErrors];
  export type ListBrandKitSectionFieldsLegacyResponses = {
    /**
     * Successful Response
     */
    200: Array<ListBrandKitSectionFieldsModelResponse>;
  };
  export type ListBrandKitSectionFieldsLegacyResponse =
    ListBrandKitSectionFieldsLegacyResponses[keyof ListBrandKitSectionFieldsLegacyResponses];
  export type CreateBrandKitSectionFieldLegacyData = {
    body: CreateBrandKitSectionFieldModelRequest;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields';
  };
  export type CreateBrandKitSectionFieldLegacyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type CreateBrandKitSectionFieldLegacyError =
    CreateBrandKitSectionFieldLegacyErrors[keyof CreateBrandKitSectionFieldLegacyErrors];
  export type CreateBrandKitSectionFieldLegacyResponses = {
    /**
     * Successful Response
     */
    201: CreateBrandKitSectionFieldModelResponse;
  };
  export type CreateBrandKitSectionFieldLegacyResponse =
    CreateBrandKitSectionFieldLegacyResponses[keyof CreateBrandKitSectionFieldLegacyResponses];
  export type ListBrandKitSectionFieldsData = {
    body?: never;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields';
  };
  export type ListBrandKitSectionFieldsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type ListBrandKitSectionFieldsError =
    ListBrandKitSectionFieldsErrors[keyof ListBrandKitSectionFieldsErrors];
  export type ListBrandKitSectionFieldsResponses = {
    /**
     * Successful Response
     */
    200: Array<ListBrandKitSectionFieldsModelResponseV2>;
  };
  export type ListBrandKitSectionFieldsResponse =
    ListBrandKitSectionFieldsResponses[keyof ListBrandKitSectionFieldsResponses];
  export type CreateBrandKitSectionFieldData = {
    body: CreateBrandKitSectionFieldModelRequestV2;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields';
  };
  export type CreateBrandKitSectionFieldErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type CreateBrandKitSectionFieldError =
    CreateBrandKitSectionFieldErrors[keyof CreateBrandKitSectionFieldErrors];
  export type CreateBrandKitSectionFieldResponses = {
    /**
     * Successful Response
     */
    201: CreateBrandKitSectionFieldModelResponseV2;
  };
  export type CreateBrandKitSectionFieldResponse =
    CreateBrandKitSectionFieldResponses[keyof CreateBrandKitSectionFieldResponses];
  export type ListBrandKitSectionFieldsV3Data = {
    body?: never;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
    };
    query?: {
      pageNumber?: number;
      pageSize?: number;
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v3/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields';
  };
  export type ListBrandKitSectionFieldsV3Errors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type ListBrandKitSectionFieldsV3Error =
    ListBrandKitSectionFieldsV3Errors[keyof ListBrandKitSectionFieldsV3Errors];
  export type ListBrandKitSectionFieldsV3Responses = {
    /**
     * Successful Response
     */
    200: ListBrandKitSectionFieldsModelResponseV3;
  };
  export type ListBrandKitSectionFieldsV3Response =
    ListBrandKitSectionFieldsV3Responses[keyof ListBrandKitSectionFieldsV3Responses];
  export type ListBrandKitSectionFieldsAdminData = {
    body?: never;
    headers: {
      'x-sc-src-tenant-id': string;
      'x-sc-ai-tenant-id'?: string;
      'x-sc-src-user-id'?: string;
    };
    path: {
      brandkitId: string;
      sectionId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/admin/v1/brandkits/{brandkitId}/sections/{sectionId}/fields';
  };
  export type ListBrandKitSectionFieldsAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type ListBrandKitSectionFieldsAdminError =
    ListBrandKitSectionFieldsAdminErrors[keyof ListBrandKitSectionFieldsAdminErrors];
  export type ListBrandKitSectionFieldsAdminResponses = {
    /**
     * Successful Response
     */
    200: Array<ListBrandKitSectionFieldsModelResponseV2>;
  };
  export type ListBrandKitSectionFieldsAdminResponse =
    ListBrandKitSectionFieldsAdminResponses[keyof ListBrandKitSectionFieldsAdminResponses];
  export type DeleteBrandKitSectionFieldData = {
    body?: never;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
      fieldId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}';
  };
  export type DeleteBrandKitSectionFieldErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type DeleteBrandKitSectionFieldError =
    DeleteBrandKitSectionFieldErrors[keyof DeleteBrandKitSectionFieldErrors];
  export type DeleteBrandKitSectionFieldResponses = {
    /**
     * Successful Response
     */
    204: void;
  };
  export type DeleteBrandKitSectionFieldResponse =
    DeleteBrandKitSectionFieldResponses[keyof DeleteBrandKitSectionFieldResponses];
  export type GetBrandKitSectionFieldLegacyData = {
    body?: never;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
      fieldId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}';
  };
  export type GetBrandKitSectionFieldLegacyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type GetBrandKitSectionFieldLegacyError =
    GetBrandKitSectionFieldLegacyErrors[keyof GetBrandKitSectionFieldLegacyErrors];
  export type GetBrandKitSectionFieldLegacyResponses = {
    /**
     * Successful Response
     */
    200: GetBrandKitSectionFieldModelResponse;
  };
  export type GetBrandKitSectionFieldLegacyResponse =
    GetBrandKitSectionFieldLegacyResponses[keyof GetBrandKitSectionFieldLegacyResponses];
  export type UpdateBrandKitSectionFieldLegacyData = {
    body: UpdateBrandKitSectionFieldModelRequest;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
      fieldId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}';
  };
  export type UpdateBrandKitSectionFieldLegacyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type UpdateBrandKitSectionFieldLegacyError =
    UpdateBrandKitSectionFieldLegacyErrors[keyof UpdateBrandKitSectionFieldLegacyErrors];
  export type UpdateBrandKitSectionFieldLegacyResponses = {
    /**
     * Successful Response
     */
    200: UpdateBrandKitSectionFieldModelResponse;
  };
  export type UpdateBrandKitSectionFieldLegacyResponse =
    UpdateBrandKitSectionFieldLegacyResponses[keyof UpdateBrandKitSectionFieldLegacyResponses];
  export type GetBrandKitSectionFieldAdminData = {
    body?: never;
    headers: {
      'x-sc-src-tenant-id': string;
      'x-sc-ai-tenant-id'?: string;
      'x-sc-src-user-id'?: string;
    };
    path: {
      brandkitId: string;
      sectionId: string;
      fieldId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/admin/v1/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}';
  };
  export type GetBrandKitSectionFieldAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type GetBrandKitSectionFieldAdminError =
    GetBrandKitSectionFieldAdminErrors[keyof GetBrandKitSectionFieldAdminErrors];
  export type GetBrandKitSectionFieldAdminResponses = {
    /**
     * Successful Response
     */
    200: GetBrandKitSectionFieldModelResponseV2;
  };
  export type GetBrandKitSectionFieldAdminResponse =
    GetBrandKitSectionFieldAdminResponses[keyof GetBrandKitSectionFieldAdminResponses];
  export type GetBrandKitSectionFieldData = {
    body?: never;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
      fieldId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}';
  };
  export type GetBrandKitSectionFieldErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type GetBrandKitSectionFieldError =
    GetBrandKitSectionFieldErrors[keyof GetBrandKitSectionFieldErrors];
  export type GetBrandKitSectionFieldResponses = {
    /**
     * Successful Response
     */
    200: GetBrandKitSectionFieldModelResponseV2;
  };
  export type GetBrandKitSectionFieldResponse =
    GetBrandKitSectionFieldResponses[keyof GetBrandKitSectionFieldResponses];
  export type UpdateBrandKitSectionFieldData = {
    body: UpdateBrandKitSectionFieldModelRequestV2;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
      fieldId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}';
  };
  export type UpdateBrandKitSectionFieldErrors = {
    /**
     * Invalid parameters
     */
    400: HttpError;
    /**
     * Resource not found
     */
    404: HttpError;
    /**
     * Brand Kit is locked
     */
    409: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Brandkit operation failed
     */
    500: HttpError;
  };
  export type UpdateBrandKitSectionFieldError =
    UpdateBrandKitSectionFieldErrors[keyof UpdateBrandKitSectionFieldErrors];
  export type UpdateBrandKitSectionFieldResponses = {
    /**
     * Successful Response
     */
    200: UpdateBrandKitSectionFieldModelResponseV2;
  };
  export type UpdateBrandKitSectionFieldResponse =
    UpdateBrandKitSectionFieldResponses[keyof UpdateBrandKitSectionFieldResponses];
  export type ListBrandKitSectionFieldReferencesData = {
    body?: never;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
      fieldId: string;
    };
    query?: {
      type?: string | null;
      pageNumber?: number;
      pageSize?: number;
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/references';
  };
  export type ListBrandKitSectionFieldReferencesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type ListBrandKitSectionFieldReferencesError =
    ListBrandKitSectionFieldReferencesErrors[keyof ListBrandKitSectionFieldReferencesErrors];
  export type ListBrandKitSectionFieldReferencesResponses = {
    /**
     * Successful Response
     */
    200: ListReferencesModelResponse;
  };
  export type ListBrandKitSectionFieldReferencesResponse =
    ListBrandKitSectionFieldReferencesResponses[keyof ListBrandKitSectionFieldReferencesResponses];
  export type CreateBrandKitSectionFieldReferenceData = {
    body: CreateBrandKitSectionFieldReferenceModelRequest;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
      fieldId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/references';
  };
  export type CreateBrandKitSectionFieldReferenceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type CreateBrandKitSectionFieldReferenceError =
    CreateBrandKitSectionFieldReferenceErrors[keyof CreateBrandKitSectionFieldReferenceErrors];
  export type CreateBrandKitSectionFieldReferenceResponses = {
    /**
     * Successful Response
     */
    201: unknown;
  };
  export type DeleteBrandKitSectonFieldReferenceData = {
    body?: never;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
      fieldId: string;
      referenceId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/references/{referenceId}';
  };
  export type DeleteBrandKitSectonFieldReferenceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type DeleteBrandKitSectonFieldReferenceError =
    DeleteBrandKitSectonFieldReferenceErrors[keyof DeleteBrandKitSectonFieldReferenceErrors];
  export type DeleteBrandKitSectonFieldReferenceResponses = {
    /**
     * Successful Response
     */
    204: void;
  };
  export type DeleteBrandKitSectonFieldReferenceResponse =
    DeleteBrandKitSectonFieldReferenceResponses[keyof DeleteBrandKitSectonFieldReferenceResponses];
  export type GetBrandKitSectionFieldReferenceData = {
    body?: never;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
      fieldId: string;
      referenceId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/references/{referenceId}';
  };
  export type GetBrandKitSectionFieldReferenceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type GetBrandKitSectionFieldReferenceError =
    GetBrandKitSectionFieldReferenceErrors[keyof GetBrandKitSectionFieldReferenceErrors];
  export type GetBrandKitSectionFieldReferenceResponses = {
    /**
     * Successful Response
     */
    200: GetReferenceModelResponse;
  };
  export type GetBrandKitSectionFieldReferenceResponse =
    GetBrandKitSectionFieldReferenceResponses[keyof GetBrandKitSectionFieldReferenceResponses];
  export type CreateBrandKitSectionFieldValueEntryData = {
    body: CreateBrandKitSectionFieldValueEntryModelRequest;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
      fieldId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/values';
  };
  export type CreateBrandKitSectionFieldValueEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type CreateBrandKitSectionFieldValueEntryError =
    CreateBrandKitSectionFieldValueEntryErrors[keyof CreateBrandKitSectionFieldValueEntryErrors];
  export type CreateBrandKitSectionFieldValueEntryResponses = {
    /**
     * Successful Response
     */
    201: CreateBrandKitSectionFieldValueEntryModelResponse;
  };
  export type CreateBrandKitSectionFieldValueEntryResponse =
    CreateBrandKitSectionFieldValueEntryResponses[keyof CreateBrandKitSectionFieldValueEntryResponses];
  export type DeleteBrandKitSectionFieldValueEntryData = {
    body?: never;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
      fieldId: string;
      entryId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/values/{entryId}';
  };
  export type DeleteBrandKitSectionFieldValueEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type DeleteBrandKitSectionFieldValueEntryError =
    DeleteBrandKitSectionFieldValueEntryErrors[keyof DeleteBrandKitSectionFieldValueEntryErrors];
  export type DeleteBrandKitSectionFieldValueEntryResponses = {
    /**
     * Successful Response
     */
    204: void;
  };
  export type DeleteBrandKitSectionFieldValueEntryResponse =
    DeleteBrandKitSectionFieldValueEntryResponses[keyof DeleteBrandKitSectionFieldValueEntryResponses];
  export type GetBrandKitSectionFieldValueEntryData = {
    body?: never;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
      fieldId: string;
      entryId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/values/{entryId}';
  };
  export type GetBrandKitSectionFieldValueEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type GetBrandKitSectionFieldValueEntryError =
    GetBrandKitSectionFieldValueEntryErrors[keyof GetBrandKitSectionFieldValueEntryErrors];
  export type GetBrandKitSectionFieldValueEntryResponses = {
    /**
     * Successful Response
     */
    200: GetBrandKitSectionFieldValueEntryModelResponse;
  };
  export type GetBrandKitSectionFieldValueEntryResponse =
    GetBrandKitSectionFieldValueEntryResponses[keyof GetBrandKitSectionFieldValueEntryResponses];
  export type UpdateBrandKitSectionFieldValueEntryData = {
    body: UpdateBrandKitSectionFieldValueEntryModelRequest;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
      fieldId: string;
      valueEntryId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/values/{valueEntryId}';
  };
  export type UpdateBrandKitSectionFieldValueEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type UpdateBrandKitSectionFieldValueEntryError =
    UpdateBrandKitSectionFieldValueEntryErrors[keyof UpdateBrandKitSectionFieldValueEntryErrors];
  export type UpdateBrandKitSectionFieldValueEntryResponses = {
    /**
     * Successful Response
     */
    200: UpdateBrandKitSectionFieldValueEntryModelResponse;
  };
  export type UpdateBrandKitSectionFieldValueEntryResponse =
    UpdateBrandKitSectionFieldValueEntryResponses[keyof UpdateBrandKitSectionFieldValueEntryResponses];
  export type CreateBrandKitSectionFieldValueEntryV2Data = {
    body: CreateBrandKitSectionFieldValueEntryModelRequestV2;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
      fieldId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/values';
  };
  export type CreateBrandKitSectionFieldValueEntryV2Errors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type CreateBrandKitSectionFieldValueEntryV2Error =
    CreateBrandKitSectionFieldValueEntryV2Errors[keyof CreateBrandKitSectionFieldValueEntryV2Errors];
  export type CreateBrandKitSectionFieldValueEntryV2Responses = {
    /**
     * Successful Response
     */
    201: CreateBrandKitSectionFieldValueEntryModelResponseV2;
  };
  export type CreateBrandKitSectionFieldValueEntryV2Response =
    CreateBrandKitSectionFieldValueEntryV2Responses[keyof CreateBrandKitSectionFieldValueEntryV2Responses];
  export type GetBrandKitSectionFieldValueEntryV2Data = {
    body?: never;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
      fieldId: string;
      valueEntryId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/values/{valueEntryId}';
  };
  export type GetBrandKitSectionFieldValueEntryV2Errors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type GetBrandKitSectionFieldValueEntryV2Error =
    GetBrandKitSectionFieldValueEntryV2Errors[keyof GetBrandKitSectionFieldValueEntryV2Errors];
  export type GetBrandKitSectionFieldValueEntryV2Responses = {
    /**
     * Successful Response
     */
    200: GetBrandKitSectionFieldValueEntryModelResponseV2;
  };
  export type GetBrandKitSectionFieldValueEntryV2Response =
    GetBrandKitSectionFieldValueEntryV2Responses[keyof GetBrandKitSectionFieldValueEntryV2Responses];
  export type UpdateBrandKitSectionFieldValueEntryV2Data = {
    body: UpdateBrandKitSectionFieldValueEntryModelRequestV2;
    path: {
      organizationId: string;
      brandkitId: string;
      sectionId: string;
      fieldId: string;
      valueEntryId: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/values/{valueEntryId}';
  };
  export type UpdateBrandKitSectionFieldValueEntryV2Errors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };
  export type UpdateBrandKitSectionFieldValueEntryV2Error =
    UpdateBrandKitSectionFieldValueEntryV2Errors[keyof UpdateBrandKitSectionFieldValueEntryV2Errors];
  export type UpdateBrandKitSectionFieldValueEntryV2Responses = {
    /**
     * Successful Response
     */
    200: UpdateBrandKitSectionFieldValueEntryModelResponseV2;
  };
  export type UpdateBrandKitSectionFieldValueEntryV2Response =
    UpdateBrandKitSectionFieldValueEntryV2Responses[keyof UpdateBrandKitSectionFieldValueEntryV2Responses];
  export type GetPublicOpenapiData = {
    body?: never;
    path?: never;
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/docs/openapi.json';
  };
  export type GetPublicOpenapiResponses = {
    /**
     * Successful Response
     */
    200: unknown;
  };
  export type GetPublicSwaggerUiData = {
    body?: never;
    path?: never;
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/docs';
  };
  export type GetPublicSwaggerUiResponses = {
    /**
     * Successful Response
     */
    200: string;
  };
  export type GetPublicSwaggerUiResponse =
    GetPublicSwaggerUiResponses[keyof GetPublicSwaggerUiResponses];
  export type GetPublicRedocUiData = {
    body?: never;
    path?: never;
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/api/docs/redoc';
  };
  export type GetPublicRedocUiResponses = {
    /**
     * Successful Response
     */
    200: string;
  };
  export type GetPublicRedocUiResponse = GetPublicRedocUiResponses[keyof GetPublicRedocUiResponses];
  export type ClientOptions = {
    baseUrl: 'https://example.com/ai-brands-api' | (string & {});
  };
}
