// This file is auto-generated by @hey-api/openapi-ts

export namespace Featureflags {
  export type GetFlagData = {
    body?: never;
    path: {
      /**
       * The name of the feature flag
       */
      name: string;
    };
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/v1/flags/{name}';
  };
  export type GetFlagErrors = {
    /**
     * Bad Request - Missing flag name
     */
    400: {
      title: string;
      type: string;
      instance: string;
      status: number;
    };
    /**
     * Not Found - Flag not found
     */
    404: {
      title: string;
      type: string;
      instance: string;
      status: number;
    };
    /**
     * Server Error
     */
    500: {
      title: string;
      type: string;
      instance: string;
      status: number;
    };
  };
  export type GetFlagError = GetFlagErrors[keyof GetFlagErrors];
  export type GetFlagResponses = {
    /**
     * Feature flag retrieved successfully
     */
    200: {
      /**
       * The name of the feature flag
       */
      name: string;
      /**
       * Whether the feature flag is enabled
       */
      enabled: boolean;
      /**
       * Number of days until the flag expires
       */
      expiryDays: number;
      /**
       * UTC timestamp of last update
       */
      lastUpdated: string;
    };
  };
  export type GetFlagResponse = GetFlagResponses[keyof GetFlagResponses];
  export type ListFlagsData = {
    body?: never;
    path?: never;
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/v1/flags';
  };
  export type ListFlagsErrors = {
    /**
     * Server Error
     */
    500: {
      title: string;
      type: string;
      instance: string;
      status: number;
    };
  };
  export type ListFlagsError = ListFlagsErrors[keyof ListFlagsErrors];
  export type ListFlagsResponses = {
    /**
     * Feature flags retrieved successfully
     */
    200: Array<{
      /**
       * The name of the feature flag
       */
      name: string;
      /**
       * Whether the feature flag is enabled
       */
      enabled: boolean;
      /**
       * Number of days until the flag expires
       */
      expiryDays: number;
      /**
       * UTC timestamp of last update
       */
      lastUpdated: string;
    }>;
  };
  export type ListFlagsResponse = ListFlagsResponses[keyof ListFlagsResponses];
  export type ListCentralizedFlagsData = {
    body?: never;
    path?: never;
    query?: {
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/v1/centralized-flags';
  };
  export type ListCentralizedFlagsErrors = {
    /**
     * Server Error
     */
    500: {
      title: string;
      type: string;
      instance: string;
      status: number;
    };
  };
  export type ListCentralizedFlagsError =
    ListCentralizedFlagsErrors[keyof ListCentralizedFlagsErrors];
  export type ListCentralizedFlagsResponses = {
    /**
     * Feature flags retrieved successfully
     */
    200: {
      featureFlagName: {
        /**
         * Number of days until the flag expires
         */
        expiryDays: number;
        /**
         * UTC timestamp of creation
         */
        createdDate: string;
        environments: {
          local: {
            /**
             * Whether the feature is enabled in this environment
             */
            enabled: boolean;
            /**
             * UTC timestamp of last update
             */
            lastUpdated: string;
          };
          dev: {
            /**
             * Whether the feature is enabled in this environment
             */
            enabled: boolean;
            /**
             * UTC timestamp of last update
             */
            lastUpdated: string;
          };
          qa: {
            /**
             * Whether the feature is enabled in this environment
             */
            enabled: boolean;
            /**
             * UTC timestamp of last update
             */
            lastUpdated: string;
          };
          staging: {
            /**
             * Whether the feature is enabled in this environment
             */
            enabled: boolean;
            /**
             * UTC timestamp of last update
             */
            lastUpdated: string;
          };
          preprod: {
            /**
             * Whether the feature is enabled in this environment
             */
            enabled: boolean;
            /**
             * UTC timestamp of last update
             */
            lastUpdated: string;
          };
          prod: {
            /**
             * Whether the feature is enabled in this environment
             */
            enabled: boolean;
            /**
             * UTC timestamp of last update
             */
            lastUpdated: string;
          };
        };
      };
    };
  };
  export type ListCentralizedFlagsResponse =
    ListCentralizedFlagsResponses[keyof ListCentralizedFlagsResponses];
  export type ClientOptions = {
    baseUrl: 'https://example.com/featureflags' | (string & {});
  };
}
