// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type TDataShape,
  type Client,
  formDataBodySerializer,
} from '@hey-api/client-fetch';
import type { Agent } from './types.gen';
import { client as _heyApiClient } from './client.gen';

type JobsListOperationsError = Agent.JobsListOperationsError;

type JobsListOperationsData = Agent.JobsListOperationsData;

type JobsGetJobError = Agent.JobsGetJobError;

type JobsGetJobData = Agent.JobsGetJobData;

type JobsRevertJobError = Agent.JobsRevertJobError;

type JobsRevertJobData = Agent.JobsRevertJobData;

type PersonalizationGetConditionTemplatesError = Agent.PersonalizationGetConditionTemplatesError;

type PersonalizationGetConditionTemplatesResponse =
  Agent.PersonalizationGetConditionTemplatesResponse;

type PersonalizationGetConditionTemplatesData = Agent.PersonalizationGetConditionTemplatesData;

type PersonalizationGetPersonalizationVersionsByPageError =
  Agent.PersonalizationGetPersonalizationVersionsByPageError;

type PersonalizationGetPersonalizationVersionsByPageResponse =
  Agent.PersonalizationGetPersonalizationVersionsByPageResponse;

type PersonalizationGetPersonalizationVersionsByPageData =
  Agent.PersonalizationGetPersonalizationVersionsByPageData;

type PersonalizationCreatePersonalizationVersionError =
  Agent.PersonalizationCreatePersonalizationVersionError;

type PersonalizationCreatePersonalizationVersionResponse =
  Agent.PersonalizationCreatePersonalizationVersionResponse;

type PersonalizationCreatePersonalizationVersionData =
  Agent.PersonalizationCreatePersonalizationVersionData;

type ExperimentsGetAbTestResultsError = Agent.ExperimentsGetAbTestResultsError;

type ExperimentsGetAbTestResultsResponse = Agent.ExperimentsGetAbTestResultsResponse;

type ExperimentsGetAbTestResultsData = Agent.ExperimentsGetAbTestResultsData;

type ExperimentsGetAbTestFlowDefinitionError = Agent.ExperimentsGetAbTestFlowDefinitionError;

type ExperimentsGetAbTestFlowDefinitionResponse = Agent.ExperimentsGetAbTestFlowDefinitionResponse;

type ExperimentsGetAbTestFlowDefinitionData = Agent.ExperimentsGetAbTestFlowDefinitionData;

type ExperimentsAddTestVariantError = Agent.ExperimentsAddTestVariantError;

type ExperimentsAddTestVariantResponse = Agent.ExperimentsAddTestVariantResponse;

type ExperimentsAddTestVariantData = Agent.ExperimentsAddTestVariantData;

type ExperimentsListPageVariantsError = Agent.ExperimentsListPageVariantsError;

type ExperimentsListPageVariantsResponse = Agent.ExperimentsListPageVariantsResponse;

type ExperimentsListPageVariantsData = Agent.ExperimentsListPageVariantsData;

type ExperimentsCreateComponentAbTestError = Agent.ExperimentsCreateComponentAbTestError;

type ExperimentsCreateComponentAbTestResponse = Agent.ExperimentsCreateComponentAbTestResponse;

type ExperimentsCreateComponentAbTestData = Agent.ExperimentsCreateComponentAbTestData;

type EnvironmentsListLanguagesError = Agent.EnvironmentsListLanguagesError;

type EnvironmentsListLanguagesResponse = Agent.EnvironmentsListLanguagesResponse;

type EnvironmentsListLanguagesData = Agent.EnvironmentsListLanguagesData;

type AssetsUpdateAssetError = Agent.AssetsUpdateAssetError;

type AssetsUpdateAssetResponse = Agent.AssetsUpdateAssetResponse;

type AssetsUpdateAssetData = Agent.AssetsUpdateAssetData;

type AssetsGetAssetInformationError = Agent.AssetsGetAssetInformationError;

type AssetsGetAssetInformationResponse = Agent.AssetsGetAssetInformationResponse;

type AssetsGetAssetInformationData = Agent.AssetsGetAssetInformationData;

type AssetsSearchAssetsError = Agent.AssetsSearchAssetsError;

type AssetsSearchAssetsResponse = Agent.AssetsSearchAssetsResponse;

type AssetsSearchAssetsData = Agent.AssetsSearchAssetsData;

type AssetsUploadAssetError = Agent.AssetsUploadAssetError;

type AssetsUploadAssetResponse = Agent.AssetsUploadAssetResponse;

type AssetsUploadAssetData = Agent.AssetsUploadAssetData;

type ComponentsGetComponentError = Agent.ComponentsGetComponentError;

type ComponentsGetComponentResponse = Agent.ComponentsGetComponentResponse;

type ComponentsGetComponentData = Agent.ComponentsGetComponentData;

type ComponentsListComponentsError = Agent.ComponentsListComponentsError;

type ComponentsListComponentsResponse = Agent.ComponentsListComponentsResponse;

type ComponentsListComponentsData = Agent.ComponentsListComponentsData;

type ComponentsSearchComponentDatasourcesError = Agent.ComponentsSearchComponentDatasourcesError;

type ComponentsSearchComponentDatasourcesResponse =
  Agent.ComponentsSearchComponentDatasourcesResponse;

type ComponentsSearchComponentDatasourcesData = Agent.ComponentsSearchComponentDatasourcesData;

type ComponentsCreateComponentDatasourceError = Agent.ComponentsCreateComponentDatasourceError;

type ComponentsCreateComponentDatasourceResponse =
  Agent.ComponentsCreateComponentDatasourceResponse;

type ComponentsCreateComponentDatasourceData = Agent.ComponentsCreateComponentDatasourceData;

type ContentListAvailableInsertoptionsError = Agent.ContentListAvailableInsertoptionsError;

type ContentListAvailableInsertoptionsResponse = Agent.ContentListAvailableInsertoptionsResponse;

type ContentListAvailableInsertoptionsData = Agent.ContentListAvailableInsertoptionsData;

type ContentGetContentItemByPathError = Agent.ContentGetContentItemByPathError;

type ContentGetContentItemByPathResponse = Agent.ContentGetContentItemByPathResponse;

type ContentGetContentItemByPathData = Agent.ContentGetContentItemByPathData;

type ContentUpdateContentError = Agent.ContentUpdateContentError;

type ContentUpdateContentResponse = Agent.ContentUpdateContentResponse;

type ContentUpdateContentData = Agent.ContentUpdateContentData;

type ContentGetContentItemByIdError = Agent.ContentGetContentItemByIdError;

type ContentGetContentItemByIdResponse = Agent.ContentGetContentItemByIdResponse;

type ContentGetContentItemByIdData = Agent.ContentGetContentItemByIdData;

type ContentDeleteContentError = Agent.ContentDeleteContentError;

type ContentDeleteContentResponse = Agent.ContentDeleteContentResponse;

type ContentDeleteContentData = Agent.ContentDeleteContentData;

type ContentCreateContentItemError = Agent.ContentCreateContentItemError;

type ContentCreateContentItemResponse = Agent.ContentCreateContentItemResponse;

type ContentCreateContentItemData = Agent.ContentCreateContentItemData;

type PagesRemoveComponentOnPageError = Agent.PagesRemoveComponentOnPageError;

type PagesRemoveComponentOnPageResponse = Agent.PagesRemoveComponentOnPageResponse;

type PagesRemoveComponentOnPageData = Agent.PagesRemoveComponentOnPageData;

type PagesGetAllowedComponentsByPlaceholderError =
  Agent.PagesGetAllowedComponentsByPlaceholderError;

type PagesGetAllowedComponentsByPlaceholderResponse =
  Agent.PagesGetAllowedComponentsByPlaceholderResponse;

type PagesGetAllowedComponentsByPlaceholderData = Agent.PagesGetAllowedComponentsByPlaceholderData;

type PagesGetPageError = Agent.PagesGetPageError;

type PagesGetPageResponse = Agent.PagesGetPageResponse;

type PagesGetPageData = Agent.PagesGetPageData;

type PagesGetPageTemplateByIdError = Agent.PagesGetPageTemplateByIdError;

type PagesGetPageTemplateByIdResponse = Agent.PagesGetPageTemplateByIdResponse;

type PagesGetPageTemplateByIdData = Agent.PagesGetPageTemplateByIdData;

type PagesGetPagePreviewUrlError = Agent.PagesGetPagePreviewUrlError;

type PagesGetPagePreviewUrlResponse = Agent.PagesGetPagePreviewUrlResponse;

type PagesGetPagePreviewUrlData = Agent.PagesGetPagePreviewUrlData;

type PagesGetPageHtmlError = Agent.PagesGetPageHtmlError;

type PagesGetPageHtmlResponse = Agent.PagesGetPageHtmlResponse;

type PagesGetPageHtmlData = Agent.PagesGetPageHtmlData;

type PagesGetPageScreenshotError = Agent.PagesGetPageScreenshotError;

type PagesGetPageScreenshotResponse = Agent.PagesGetPageScreenshotResponse;

type PagesGetPageScreenshotData = Agent.PagesGetPageScreenshotData;

type PagesGetPagePathByLiveUrlError = Agent.PagesGetPagePathByLiveUrlError;

type PagesGetPagePathByLiveUrlResponse = Agent.PagesGetPagePathByLiveUrlResponse;

type PagesGetPagePathByLiveUrlData = Agent.PagesGetPagePathByLiveUrlData;

type PagesSearchSiteError = Agent.PagesSearchSiteError;

type PagesSearchSiteResponse = Agent.PagesSearchSiteResponse;

type PagesSearchSiteData = Agent.PagesSearchSiteData;

type PagesSetComponentDatasourceError = Agent.PagesSetComponentDatasourceError;

type PagesSetComponentDatasourceResponse = Agent.PagesSetComponentDatasourceResponse;

type PagesSetComponentDatasourceData = Agent.PagesSetComponentDatasourceData;

type PagesAddComponentOnPageError = Agent.PagesAddComponentOnPageError;

type PagesAddComponentOnPageResponse = Agent.PagesAddComponentOnPageResponse;

type PagesAddComponentOnPageData = Agent.PagesAddComponentOnPageData;

type PagesGetComponentsOnPageError = Agent.PagesGetComponentsOnPageError;

type PagesGetComponentsOnPageResponse = Agent.PagesGetComponentsOnPageResponse;

type PagesGetComponentsOnPageData = Agent.PagesGetComponentsOnPageData;

type PagesAddLanguageToPageError = Agent.PagesAddLanguageToPageError;

type PagesAddLanguageToPageResponse = Agent.PagesAddLanguageToPageResponse;

type PagesAddLanguageToPageData = Agent.PagesAddLanguageToPageData;

type PagesCreatePageError = Agent.PagesCreatePageError;

type PagesCreatePageResponse = Agent.PagesCreatePageResponse;

type PagesCreatePageData = Agent.PagesCreatePageData;

type SitesGetSiteIdFromItemError = Agent.SitesGetSiteIdFromItemError;

type SitesGetSiteIdFromItemResponse = Agent.SitesGetSiteIdFromItemResponse;

type SitesGetSiteIdFromItemData = Agent.SitesGetSiteIdFromItemData;

type SitesGetAllPagesBySiteError = Agent.SitesGetAllPagesBySiteError;

type SitesGetAllPagesBySiteResponse = Agent.SitesGetAllPagesBySiteResponse;

type SitesGetAllPagesBySiteData = Agent.SitesGetAllPagesBySiteData;

type SitesGetSiteDetailsError = Agent.SitesGetSiteDetailsError;

type SitesGetSiteDetailsResponse = Agent.SitesGetSiteDetailsResponse;

type SitesGetSiteDetailsData = Agent.SitesGetSiteDetailsData;

type SitesGetSitesListError = Agent.SitesGetSitesListError;

type SitesGetSitesListResponse = Agent.SitesGetSitesListResponse;

type SitesGetSitesListData = Agent.SitesGetSitesListData;

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get sites list
 * Retrieves a list of all available sites with their basic information and configuration.
 */
export const sitesGetSitesList = <ThrowOnError extends boolean = false>(
  options?: Options<SitesGetSitesListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    SitesGetSitesListResponse,
    SitesGetSitesListError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/sites',
    ...options,
  });
};

/**
 * Get site details
 * Retrieves detailed information about a specific site including its configuration, themes, and available languages.
 */
export const sitesGetSiteDetails = <ThrowOnError extends boolean = false>(
  options: Options<SitesGetSiteDetailsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    SitesGetSiteDetailsResponse,
    SitesGetSiteDetailsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/sites/{siteId}',
    ...options,
  });
};

/**
 * Get all routes by site
 * Returns a flat list of routes for the specified site and language, each with id and path.
 */
export const sitesGetAllPagesBySite = <ThrowOnError extends boolean = false>(
  options: Options<SitesGetAllPagesBySiteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    SitesGetAllPagesBySiteResponse,
    SitesGetAllPagesBySiteError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/sites/{siteName}/pages',
    ...options,
  });
};

/**
 * Get site ID from item ID
 * Returns the site root item ID for a given item by traversing ancestors to find the site root template
 */
export const sitesGetSiteIdFromItem = <ThrowOnError extends boolean = false>(
  options: Options<SitesGetSiteIdFromItemData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    SitesGetSiteIdFromItemResponse,
    SitesGetSiteIdFromItemError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/sites/site-id-from-item/{itemId}',
    ...options,
  });
};

/**
 * Create a page
 * Creates a new page in the specified location with the given template, fields, and language. The page is created as a child of the specified parent page.
 */
export const pagesCreatePage = <ThrowOnError extends boolean = false>(
  options: Options<PagesCreatePageData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PagesCreatePageResponse,
    PagesCreatePageError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/pages/create',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Add language to page
 * Creates a language version of an existing page. This allows you to have the same page content available in multiple languages.
 */
export const pagesAddLanguageToPage = <ThrowOnError extends boolean = false>(
  options: Options<PagesAddLanguageToPageData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PagesAddLanguageToPageResponse,
    PagesAddLanguageToPageError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/pages/{pageId}/add-language',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Get components on page
 * Retrieves a list of components that are currently added to a specific page.
 */
export const pagesGetComponentsOnPage = <ThrowOnError extends boolean = false>(
  options: Options<PagesGetComponentsOnPageData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PagesGetComponentsOnPageResponse,
    PagesGetComponentsOnPageError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/pages/{pageId}/components',
    ...options,
  });
};

/**
 * Add component on page
 * Adds a component to a specific placeholder on a page. You can optionally specify a datasource for the component or create a new one.
 */
export const pagesAddComponentOnPage = <ThrowOnError extends boolean = false>(
  options: Options<PagesAddComponentOnPageData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PagesAddComponentOnPageResponse,
    PagesAddComponentOnPageError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/pages/{pageId}/components',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Sets the component's datasource
 * Set component datasource
 */
export const pagesSetComponentDatasource = <ThrowOnError extends boolean = false>(
  options: Options<PagesSetComponentDatasourceData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PagesSetComponentDatasourceResponse,
    PagesSetComponentDatasourceError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/pages/{pageId}/components/{componentId}/datasource',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Search site
 * Searches all pages in a specific site by title or content. The response returns the matching pages with their details including id, path, display_name, and search_fields.
 */
export const pagesSearchSite = <ThrowOnError extends boolean = false>(
  options: Options<PagesSearchSiteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PagesSearchSiteResponse,
    PagesSearchSiteError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/pages/search',
    ...options,
  });
};

/**
 * Get page path by live URL
 * Get the page item path corresponding to a live URL. You can use this endpoint to find the page item that corresponds to a specific live URL on your website.
 */
export const pagesGetPagePathByLiveUrl = <ThrowOnError extends boolean = false>(
  options: Options<PagesGetPagePathByLiveUrlData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PagesGetPagePathByLiveUrlResponse,
    PagesGetPagePathByLiveUrlError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/pages/path-by-url',
    ...options,
  });
};

/**
 * Get page screenshot
 * Captures and returns a screenshot of the specified page. This endpoint takes a screenshot of the live page and returns it as a base64-encoded image.
 */
export const pagesGetPageScreenshot = <ThrowOnError extends boolean = false>(
  options: Options<PagesGetPageScreenshotData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PagesGetPageScreenshotResponse,
    PagesGetPageScreenshotError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/pages/{pageId}/screenshot',
    ...options,
  });
};

/**
 * Get page HTML
 * Retrieves the HTML content of a specific page. This endpoint returns the raw HTML of the page as it would appear in the browser.
 */
export const pagesGetPageHtml = <ThrowOnError extends boolean = false>(
  options: Options<PagesGetPageHtmlData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PagesGetPageHtmlResponse,
    PagesGetPageHtmlError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/pages/{pageId}/html',
    ...options,
  });
};

/**
 * Get page Preview URL
 * Retrieves the preview URL of a specific page. This endpoint returns the URL that can be used to preview the page.
 */
export const pagesGetPagePreviewUrl = <ThrowOnError extends boolean = false>(
  options: Options<PagesGetPagePreviewUrlData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PagesGetPagePreviewUrlResponse,
    PagesGetPagePreviewUrlError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/pages/{pageId}/preview-url',
    ...options,
  });
};

/**
 * Get page template by id
 * Retrieves detailed information about a specific page template, including its fields and settings. Use this endpoint to understand the structure and available fields of a template before creating pages.
 */
export const pagesGetPageTemplateById = <ThrowOnError extends boolean = false>(
  options: Options<PagesGetPageTemplateByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PagesGetPageTemplateByIdResponse,
    PagesGetPageTemplateByIdError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/pages/template-by-id',
    ...options,
  });
};

/**
 * Get page details
 * Retrieves comprehensive information about a page including its layout, components, placeholders, and available actions. This endpoint provides all the information needed to understand and modify a page.
 */
export const pagesGetPage = <ThrowOnError extends boolean = false>(
  options: Options<PagesGetPageData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PagesGetPageResponse,
    PagesGetPageError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/pages/{pageId}',
    ...options,
  });
};

/**
 * Get allowed components by placeholder
 * Retrieves a list of components that are allowed to be added to a specific placeholder on a page. This helps ensure only compatible components are added to each placeholder.
 */
export const pagesGetAllowedComponentsByPlaceholder = <ThrowOnError extends boolean = false>(
  options: Options<PagesGetAllowedComponentsByPlaceholderData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PagesGetAllowedComponentsByPlaceholderResponse,
    PagesGetAllowedComponentsByPlaceholderError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/pages/{pageId}/placeholders/{placeholderName}/allowed-components',
    ...options,
  });
};

/**
 * @deprecated
 * Remove component on page
 * Removes a specific component from a page. The component is completely removed from the specified placeholder.
 */
export const pagesRemoveComponentOnPage = <ThrowOnError extends boolean = false>(
  options: Options<PagesRemoveComponentOnPageData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    PagesRemoveComponentOnPageResponse,
    PagesRemoveComponentOnPageError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/pages/{pageId}/components/{componentId}',
    ...options,
  });
};

/**
 * Create content item
 * Creates a new content item with the specified template, fields, and location.
 */
export const contentCreateContentItem = <ThrowOnError extends boolean = false>(
  options: Options<ContentCreateContentItemData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ContentCreateContentItemResponse,
    ContentCreateContentItemError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/content/create',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete content
 * Deletes a content item and optionally all its child items.
 */
export const contentDeleteContent = <ThrowOnError extends boolean = false>(
  options: Options<ContentDeleteContentData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    ContentDeleteContentResponse,
    ContentDeleteContentError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/content/{itemId}',
    ...options,
  });
};

/**
 * Get content item by ID
 * Retrieves detailed information about a specific content item using its unique identifier.
 */
export const contentGetContentItemById = <ThrowOnError extends boolean = false>(
  options: Options<ContentGetContentItemByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ContentGetContentItemByIdResponse,
    ContentGetContentItemByIdError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/content/{itemId}',
    ...options,
  });
};

/**
 * Update content
 * Updates comprehensive information about a content item including its fields and metadata.
 */
export const contentUpdateContent = <ThrowOnError extends boolean = false>(
  options: Options<ContentUpdateContentData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    ContentUpdateContentResponse,
    ContentUpdateContentError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/content/{itemId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Get content item by path
 * Retrieves detailed information about a content item using its path in the content tree.
 */
export const contentGetContentItemByPath = <ThrowOnError extends boolean = false>(
  options: Options<ContentGetContentItemByPathData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ContentGetContentItemByPathResponse,
    ContentGetContentItemByPathError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/content',
    ...options,
  });
};

/**
 * List available insert options
 * Retrieves the available content templates that can be inserted as child items under the specified parent item.
 */
export const contentListAvailableInsertoptions = <ThrowOnError extends boolean = false>(
  options: Options<ContentListAvailableInsertoptionsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ContentListAvailableInsertoptionsResponse,
    ContentListAvailableInsertoptionsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/content/{itemId}/insert-options',
    ...options,
  });
};

/**
 * Create component datasource
 * Creates a new datasource item for a specific component with the provided field values. The datasource will be created in the appropriate location based on the component's configuration.
 */
export const componentsCreateComponentDatasource = <ThrowOnError extends boolean = false>(
  options: Options<ComponentsCreateComponentDatasourceData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ComponentsCreateComponentDatasourceResponse,
    ComponentsCreateComponentDatasourceError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/components/{componentId}/datasources',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Search component datasources
 * Searches for available datasources that can be used with a specific component. This helps find existing content items that can serve as datasources.
 */
export const componentsSearchComponentDatasources = <ThrowOnError extends boolean = false>(
  options: Options<ComponentsSearchComponentDatasourcesData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ComponentsSearchComponentDatasourcesResponse,
    ComponentsSearchComponentDatasourcesError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/components/{componentId}/datasources/search',
    ...options,
  });
};

/**
 * List components
 * Retrieves a list of all available components for a specific site. This includes both built-in components and custom components that can be used in pages.
 */
export const componentsListComponents = <ThrowOnError extends boolean = false>(
  options: Options<ComponentsListComponentsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ComponentsListComponentsResponse,
    ComponentsListComponentsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/components',
    ...options,
  });
};

/**
 * Get component details
 * Retrieves detailed information about a specific component including its fields, datasource requirements, and configuration options.
 */
export const componentsGetComponent = <ThrowOnError extends boolean = false>(
  options: Options<ComponentsGetComponentData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ComponentsGetComponentResponse,
    ComponentsGetComponentError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/components/{componentId}',
    ...options,
  });
};

/**
 * Upload asset
 * Uploads a new digital asset to the system. The asset will be processed and stored in the specified location with the provided metadata.
 */
export const assetsUploadAsset = <ThrowOnError extends boolean = false>(
  options: Options<AssetsUploadAssetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    AssetsUploadAssetResponse,
    AssetsUploadAssetError,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/assets/upload',
    ...options,
    headers: {
      'Content-Type': null,
      ...options?.headers,
    },
  });
};

/**
 * Search assets
 * Searches for digital assets based on query terms, file types, or tags. Returns a list of matching assets with their metadata and download URLs.
 */
export const assetsSearchAssets = <ThrowOnError extends boolean = false>(
  options?: Options<AssetsSearchAssetsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    AssetsSearchAssetsResponse,
    AssetsSearchAssetsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/assets/search',
    ...options,
  });
};

/**
 * Get asset information
 * Retrieves detailed information about a specific digital asset including its metadata, file properties, and usage information.
 */
export const assetsGetAssetInformation = <ThrowOnError extends boolean = false>(
  options: Options<AssetsGetAssetInformationData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    AssetsGetAssetInformationResponse,
    AssetsGetAssetInformationError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/assets/{assetId}',
    ...options,
  });
};

/**
 * Update asset
 * Updates the metadata and properties of an existing digital asset. This allows you to modify asset information such as alt text, titles, and custom field values.
 */
export const assetsUpdateAsset = <ThrowOnError extends boolean = false>(
  options: Options<AssetsUpdateAssetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    AssetsUpdateAssetResponse,
    AssetsUpdateAssetError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/assets/{assetId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * List languages
 * Retrieves all languages available.
 */
export const environmentsListLanguages = <ThrowOnError extends boolean = false>(
  options?: Options<EnvironmentsListLanguagesData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    EnvironmentsListLanguagesResponse,
    EnvironmentsListLanguagesError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/environments/languages',
    ...options,
  });
};

/**
 * @deprecated
 * Create component A/B test
 * Creates a new A/B test for a specific component on a page. The test will allow you to compare different versions of the component to determine which performs better.
 */
export const experimentsCreateComponentAbTest = <ThrowOnError extends boolean = false>(
  options: Options<ExperimentsCreateComponentAbTestData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ExperimentsCreateComponentAbTestResponse,
    ExperimentsCreateComponentAbTestError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/experiments/ab-tests',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * List page tests
 * Retrieves all experiments currently running or completed for a specific page. This includes A/B tests, multivariate tests, and personalization experiments.
 */
export const experimentsListPageVariants = <ThrowOnError extends boolean = false>(
  options: Options<ExperimentsListPageVariantsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ExperimentsListPageVariantsResponse,
    ExperimentsListPageVariantsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/experiments/by-page/{pageId}',
    ...options,
  });
};

/**
 * @deprecated
 * Add test variant
 * Adds a new variant to an existing experiment. This allows you to test additional versions beyond the original A/B test setup.
 */
export const experimentsAddTestVariant = <ThrowOnError extends boolean = false>(
  options: Options<ExperimentsAddTestVariantData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ExperimentsAddTestVariantResponse,
    ExperimentsAddTestVariantError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/experiments/{testId}/variants',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * @deprecated
 * Get A/B test flow definition
 * Retrieves the flow definition for a specific experiment, including the test structure, goals, and configuration details.
 */
export const experimentsGetAbTestFlowDefinition = <ThrowOnError extends boolean = false>(
  options: Options<ExperimentsGetAbTestFlowDefinitionData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ExperimentsGetAbTestFlowDefinitionResponse,
    ExperimentsGetAbTestFlowDefinitionError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/experiments/flows/{flowId}',
    ...options,
  });
};

/**
 * @deprecated
 * Get A/B test results
 * Retrieves the results and performance metrics for a specific experiment, including conversion rates, statistical significance, and variant performance.
 */
export const experimentsGetAbTestResults = <ThrowOnError extends boolean = false>(
  options: Options<ExperimentsGetAbTestResultsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ExperimentsGetAbTestResultsResponse,
    ExperimentsGetAbTestResultsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/experiments/{testId}/results',
    ...options,
  });
};

/**
 * @deprecated
 * Create personalization version
 * Creates a new personalization version for a page, allowing you to deliver tailored content to specific audience segments based on their behavior and preferences.
 */
export const personalizationCreatePersonalizationVersion = <ThrowOnError extends boolean = false>(
  options: Options<PersonalizationCreatePersonalizationVersionData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PersonalizationCreatePersonalizationVersionResponse,
    PersonalizationCreatePersonalizationVersionError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/personalization/{pageId}/versions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Get personalization versions by page
 * Retrieves all personalization versions configured for a specific page, including their targeting rules and content variations.
 */
export const personalizationGetPersonalizationVersionsByPage = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PersonalizationGetPersonalizationVersionsByPageData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    PersonalizationGetPersonalizationVersionsByPageResponse,
    PersonalizationGetPersonalizationVersionsByPageError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/personalization/by-page/{pageId}',
    ...options,
  });
};

/**
 * Get personalization condition templates
 * Retrieves all available condition templates for personalization.
 */
export const personalizationGetConditionTemplates = <ThrowOnError extends boolean = false>(
  options?: Options<PersonalizationGetConditionTemplatesData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    PersonalizationGetConditionTemplatesResponse,
    PersonalizationGetConditionTemplatesError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/personalization/condition-templates',
    ...options,
  });
};

/**
 * Revert Job
 * Reverts the operations of the specified job.
 */
export const jobsRevertJob = <ThrowOnError extends boolean = false>(
  options: Options<JobsRevertJobData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<unknown, JobsRevertJobError, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/jobs/{jobId}/revert',
    ...options,
  });
};

/**
 * Get Job Details
 * Retrieves the details of the specified job.
 */
export const jobsGetJob = <ThrowOnError extends boolean = false>(
  options: Options<JobsGetJobData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<unknown, JobsGetJobError, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/jobs/{jobId}',
    ...options,
  });
};

/**
 * List Job Operations
 * Retrieves the operations associated with the specified job.
 */
export const jobsListOperations = <ThrowOnError extends boolean = false>(
  options: Options<JobsListOperationsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<unknown, JobsListOperationsError, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/jobs/{jobId}/operations',
    ...options,
  });
};
