// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { experimental_Featureflags } from './types.gen';
import { client as _heyApiClient } from './client.gen';

type ListCentralizedFlagsError = experimental_Featureflags.ListCentralizedFlagsError;

type ListCentralizedFlagsResponse = experimental_Featureflags.ListCentralizedFlagsResponse;

type ListCentralizedFlagsData = experimental_Featureflags.ListCentralizedFlagsData;

type ListFlagsError = experimental_Featureflags.ListFlagsError;

type ListFlagsResponse = experimental_Featureflags.ListFlagsResponse;

type ListFlagsData = experimental_Featureflags.ListFlagsData;

type GetFlagError = experimental_Featureflags.GetFlagError;

type GetFlagResponse = experimental_Featureflags.GetFlagResponse;

type GetFlagData = experimental_Featureflags.GetFlagData;

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get feature flag info of the current environment
 * Retrieve a specific feature flag by name.
 */
export const getFlag = <ThrowOnError extends boolean = false>(
  options: Options<GetFlagData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetFlagResponse, GetFlagError, ThrowOnError>({
    url: '/v1/flags/{name}',
    ...options,
  });
};

/**
 * List feature flags of the current environment
 * Retrieve all feature flags.
 */
export const listFlags = <ThrowOnError extends boolean = false>(
  options?: Options<ListFlagsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<ListFlagsResponse, ListFlagsError, ThrowOnError>({
    url: '/v1/flags',
    ...options,
  });
};

/**
 * List feature flags info from centralized flags
 * Retrieve all feature flags from centralized flags.
 */
export const listCentralizedFlags = <ThrowOnError extends boolean = false>(
  options?: Options<ListCentralizedFlagsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListCentralizedFlagsResponse,
    ListCentralizedFlagsError,
    ThrowOnError
  >({
    url: '/v1/centralized-flags',
    ...options,
  });
};
