// This file is auto-generated by @hey-api/openapi-ts

export const CreateExtractionRequestModelSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    description: {
      type: 'string',
      title: 'Description',
    },
    systemPrompt: {
      type: 'string',
      title: 'Systemprompt',
    },
    prompt: {
      type: 'string',
      title: 'Prompt',
    },
    input: {
      anyOf: [
        {
          additionalProperties: true,
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Input',
    },
    attributes: {
      anyOf: [
        {
          additionalProperties: true,
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Attributes',
    },
    context: {
      anyOf: [
        {
          items: {
            additionalProperties: true,
            type: 'object',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Context',
    },
    examples: {
      anyOf: [
        {
          items: {
            additionalProperties: true,
            type: 'object',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Examples',
    },
    output: {
      additionalProperties: true,
      type: 'object',
      title: 'Output',
    },
    model: {
      anyOf: [
        {
          $ref: '#/components/schemas/LLMModel',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  type: 'object',
  required: ['name', 'description', 'systemPrompt', 'prompt', 'output'],
  title: 'CreateExtractionRequestModel',
} as const;

export const CreateExtractionResponseModelSchema = {
  properties: {
    createdBy: {
      type: 'string',
      title: 'Createdby',
    },
    createdOn: {
      type: 'string',
      title: 'Createdon',
    },
    updatedBy: {
      type: 'string',
      title: 'Updatedby',
    },
    updatedOn: {
      type: 'string',
      title: 'Updatedon',
    },
    name: {
      type: 'string',
      title: 'Name',
    },
    description: {
      type: 'string',
      title: 'Description',
    },
    systemPrompt: {
      type: 'string',
      title: 'Systemprompt',
    },
    prompt: {
      type: 'string',
      title: 'Prompt',
    },
    input: {
      anyOf: [
        {
          additionalProperties: true,
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Input',
    },
    attributes: {
      anyOf: [
        {
          additionalProperties: true,
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Attributes',
    },
    context: {
      anyOf: [
        {
          items: {
            additionalProperties: true,
            type: 'object',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Context',
    },
    examples: {
      anyOf: [
        {
          items: {
            additionalProperties: true,
            type: 'object',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Examples',
    },
    output: {
      additionalProperties: true,
      type: 'object',
      title: 'Output',
    },
    model: {
      anyOf: [
        {
          $ref: '#/components/schemas/LLMModel',
        },
        {
          type: 'null',
        },
      ],
    },
    id: {
      type: 'string',
      format: 'uuid',
      title: 'Id',
    },
    version: {
      type: 'integer',
      title: 'Version',
    },
  },
  type: 'object',
  required: [
    'createdBy',
    'createdOn',
    'updatedBy',
    'updatedOn',
    'name',
    'description',
    'systemPrompt',
    'prompt',
    'output',
    'version',
  ],
  title: 'CreateExtractionResponseModel',
} as const;

export const ExtractionSchema = {
  properties: {
    createdBy: {
      type: 'string',
      title: 'Createdby',
    },
    createdOn: {
      type: 'string',
      title: 'Createdon',
    },
    updatedBy: {
      type: 'string',
      title: 'Updatedby',
    },
    updatedOn: {
      type: 'string',
      title: 'Updatedon',
    },
    name: {
      type: 'string',
      title: 'Name',
    },
    description: {
      type: 'string',
      title: 'Description',
    },
    systemPrompt: {
      type: 'string',
      title: 'Systemprompt',
    },
    prompt: {
      type: 'string',
      title: 'Prompt',
    },
    input: {
      anyOf: [
        {
          additionalProperties: true,
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Input',
    },
    attributes: {
      anyOf: [
        {
          additionalProperties: true,
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Attributes',
    },
    context: {
      anyOf: [
        {
          items: {
            additionalProperties: true,
            type: 'object',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Context',
    },
    examples: {
      anyOf: [
        {
          items: {
            additionalProperties: true,
            type: 'object',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Examples',
    },
    output: {
      additionalProperties: true,
      type: 'object',
      title: 'Output',
    },
    model: {
      anyOf: [
        {
          $ref: '#/components/schemas/LLMModel',
        },
        {
          type: 'null',
        },
      ],
    },
    id: {
      type: 'string',
      format: 'uuid',
      title: 'Id',
    },
    version: {
      type: 'integer',
      title: 'Version',
    },
  },
  type: 'object',
  required: [
    'createdBy',
    'createdOn',
    'updatedBy',
    'updatedOn',
    'name',
    'description',
    'systemPrompt',
    'prompt',
    'output',
    'version',
  ],
  title: 'Extraction',
} as const;

export const GenerateExtractionModelRequestSchema = {
  properties: {
    name: {
      type: 'string',
      title: 'Name',
    },
    description: {
      type: 'string',
      title: 'Description',
    },
    systemPrompt: {
      type: 'string',
      title: 'Systemprompt',
    },
    prompt: {
      type: 'string',
      title: 'Prompt',
    },
    input: {
      additionalProperties: true,
      type: 'object',
      title: 'Input',
    },
    attributes: {
      additionalProperties: true,
      type: 'object',
      title: 'Attributes',
    },
    context: {
      items: {
        additionalProperties: true,
        type: 'object',
      },
      type: 'array',
      title: 'Context',
    },
    examples: {
      items: {
        additionalProperties: true,
        type: 'object',
      },
      type: 'array',
      title: 'Examples',
    },
    temperature: {
      type: 'number',
      maximum: 2,
      minimum: 0,
      title: 'Temperature',
      default: 1,
    },
    model: {
      anyOf: [
        {
          $ref: '#/components/schemas/LLMModel',
        },
        {
          type: 'null',
        },
      ],
    },
    reasoningEffort: {
      anyOf: [
        {
          type: 'string',
          enum: ['minimal', 'low', 'medium', 'high'],
        },
        {
          type: 'null',
        },
      ],
      title: 'Reasoningeffort',
    },
    verbosity: {
      anyOf: [
        {
          type: 'string',
          enum: ['low', 'medium', 'high'],
        },
        {
          type: 'null',
        },
      ],
      title: 'Verbosity',
      default: 'medium',
    },
  },
  type: 'object',
  required: ['name', 'description', 'systemPrompt', 'prompt'],
  title: 'GenerateExtractionModelRequest',
} as const;

export const GetExtractionResponseModelSchema = {
  properties: {
    createdBy: {
      type: 'string',
      title: 'Createdby',
    },
    createdOn: {
      type: 'string',
      title: 'Createdon',
    },
    updatedBy: {
      type: 'string',
      title: 'Updatedby',
    },
    updatedOn: {
      type: 'string',
      title: 'Updatedon',
    },
    name: {
      type: 'string',
      title: 'Name',
    },
    description: {
      type: 'string',
      title: 'Description',
    },
    systemPrompt: {
      type: 'string',
      title: 'Systemprompt',
    },
    prompt: {
      type: 'string',
      title: 'Prompt',
    },
    input: {
      anyOf: [
        {
          additionalProperties: true,
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Input',
    },
    attributes: {
      anyOf: [
        {
          additionalProperties: true,
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Attributes',
    },
    context: {
      anyOf: [
        {
          items: {
            additionalProperties: true,
            type: 'object',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Context',
    },
    examples: {
      anyOf: [
        {
          items: {
            additionalProperties: true,
            type: 'object',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Examples',
    },
    output: {
      additionalProperties: true,
      type: 'object',
      title: 'Output',
    },
    model: {
      anyOf: [
        {
          $ref: '#/components/schemas/LLMModel',
        },
        {
          type: 'null',
        },
      ],
    },
    id: {
      type: 'string',
      format: 'uuid',
      title: 'Id',
    },
    version: {
      type: 'integer',
      title: 'Version',
    },
  },
  type: 'object',
  required: [
    'createdBy',
    'createdOn',
    'updatedBy',
    'updatedOn',
    'name',
    'description',
    'systemPrompt',
    'prompt',
    'output',
    'version',
  ],
  title: 'GetExtractionResponseModel',
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: '#/components/schemas/ValidationError',
      },
      type: 'array',
      title: 'Detail',
    },
  },
  type: 'object',
  title: 'HTTPValidationError',
} as const;

export const LLMModelSchema = {
  properties: {
    extraction: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Extraction',
    },
  },
  type: 'object',
  title: 'LLMModel',
  description: 'Custom LLM models in the requests that override the default LLM models.',
} as const;

export const ListExtractionsModelResponseSchema = {
  properties: {
    totalCount: {
      type: 'integer',
      title: 'Totalcount',
      default: 1,
    },
    pageSize: {
      type: 'integer',
      maximum: 100,
      minimum: 1,
      title: 'Pagesize',
      default: 50,
    },
    pageNumber: {
      type: 'integer',
      title: 'Pagenumber',
      default: 1,
    },
    data: {
      items: {
        anyOf: [
          {
            $ref: '#/components/schemas/Extraction',
          },
          {
            type: 'null',
          },
        ],
      },
      type: 'array',
      title: 'Data',
      default: [],
    },
  },
  additionalProperties: true,
  type: 'object',
  title: 'ListExtractionsModelResponse',
} as const;

export const UpdateExtractionRequestModelSchema = {
  properties: {
    output: {
      additionalProperties: true,
      type: 'object',
      title: 'Output',
    },
    model: {
      anyOf: [
        {
          $ref: '#/components/schemas/LLMModel',
        },
        {
          type: 'null',
        },
      ],
    },
  },
  type: 'object',
  required: ['output'],
  title: 'UpdateExtractionRequestModel',
} as const;

export const UpdateExtractionResponseModelSchema = {
  properties: {
    createdBy: {
      type: 'string',
      title: 'Createdby',
    },
    createdOn: {
      type: 'string',
      title: 'Createdon',
    },
    updatedBy: {
      type: 'string',
      title: 'Updatedby',
    },
    updatedOn: {
      type: 'string',
      title: 'Updatedon',
    },
    name: {
      type: 'string',
      title: 'Name',
    },
    description: {
      type: 'string',
      title: 'Description',
    },
    systemPrompt: {
      type: 'string',
      title: 'Systemprompt',
    },
    prompt: {
      type: 'string',
      title: 'Prompt',
    },
    input: {
      anyOf: [
        {
          additionalProperties: true,
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Input',
    },
    attributes: {
      anyOf: [
        {
          additionalProperties: true,
          type: 'object',
        },
        {
          type: 'null',
        },
      ],
      title: 'Attributes',
    },
    context: {
      anyOf: [
        {
          items: {
            additionalProperties: true,
            type: 'object',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Context',
    },
    examples: {
      anyOf: [
        {
          items: {
            additionalProperties: true,
            type: 'object',
          },
          type: 'array',
        },
        {
          type: 'null',
        },
      ],
      title: 'Examples',
    },
    output: {
      additionalProperties: true,
      type: 'object',
      title: 'Output',
    },
    model: {
      anyOf: [
        {
          $ref: '#/components/schemas/LLMModel',
        },
        {
          type: 'null',
        },
      ],
    },
    id: {
      type: 'string',
      format: 'uuid',
      title: 'Id',
    },
    version: {
      type: 'integer',
      title: 'Version',
    },
  },
  type: 'object',
  required: [
    'createdBy',
    'createdOn',
    'updatedBy',
    'updatedOn',
    'name',
    'description',
    'systemPrompt',
    'prompt',
    'output',
    'version',
  ],
  title: 'UpdateExtractionResponseModel',
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: 'string',
          },
          {
            type: 'integer',
          },
        ],
      },
      type: 'array',
      title: 'Location',
    },
    msg: {
      type: 'string',
      title: 'Message',
    },
    type: {
      type: 'string',
      title: 'Error Type',
    },
    input: {
      title: 'Input',
    },
    ctx: {
      type: 'object',
      title: 'Context',
    },
  },
  type: 'object',
  required: ['loc', 'msg', 'type'],
  title: 'ValidationError',
} as const;
