openapi: 3.0.3
info:
  title: Sitecore GraphQL API
  version: 1.0.0
servers:
  - url: https://example.com/v1/authoring
security:
  - Bearer: []
components:
  securitySchemes:
    Bearer:
      type: http
      description: Enter your bearer token in the text input below.
      scheme: Bearer
paths:
  /graphql:
    post:
      summary: Execute a GraphQL query or mutation
      description: Send a GraphQL query or mutation request to the Sitecore Authoring API. Both queries and mutations are supported.
      operationId: graphql
      security:
        - Bearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: The GraphQL query or mutation string
                  example: |
                    # Sitecore Authoring API example
                    mutation {
                      updateItem(id: "12345", fields: { title: "Updated Title" }) {
                        id
                        name
                        fields {
                          title {
                            value
                          }
                        }
                      }
                    }
                variables:
                  type: object
                  additionalProperties: {}
                  description: Optional variables for the GraphQL query or mutation
                  example: { 'id': '12345' }
                operationName:
                  type: string
                  nullable: true
                  description: Name of the operation if multiple operations are provided
                  example: 'UpdateItem'
      responses:
        '200':
          description: Successful GraphQL response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    description: GraphQL response data
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                        locations:
                          type: array
                          items:
                            type: object
                            properties:
                              line:
                                type: integer
                              column:
                                type: integer
                        path:
                          type: array
                          items:
                            type: string
        '400':
          description: Bad request (e.g., syntax error in query)
        '401':
          description: Unauthorized request (missing or invalid authentication)
        '500':
          description: Internal server error
