// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { Skills } from './types.gen';
import { client as _heyApiClient } from './client.gen';

type GenerateBrandReviewError = Skills.GenerateBrandReviewError;

type GenerateBrandReviewData = Skills.GenerateBrandReviewData;

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Generate Brand Review
 * Runs the input against the brand definition and generates a brand review leveraging a large language model (LLM). It considers the content of the brand kit sections and subsections to deliver compliance scores, explanations, and fix suggestions.
 */
export const generateBrandReview = <ThrowOnError extends boolean = false>(
  options: Options<GenerateBrandReviewData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<unknown, GenerateBrandReviewError, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/skills/v1/brandreview/generate',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};
