// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { experimental_Brands } from './types.gen';
import { client as _heyApiClient } from './client.gen';

type GetPublicRedocUiResponse = experimental_Brands.GetPublicRedocUiResponse;

type GetPublicRedocUiData = experimental_Brands.GetPublicRedocUiData;

type GetPublicSwaggerUiResponse = experimental_Brands.GetPublicSwaggerUiResponse;

type GetPublicSwaggerUiData = experimental_Brands.GetPublicSwaggerUiData;

type GetPublicOpenapiData = experimental_Brands.GetPublicOpenapiData;

type UpdateBrandKitSectionFieldValueEntryV2Error =
  experimental_Brands.UpdateBrandKitSectionFieldValueEntryV2Error;

type UpdateBrandKitSectionFieldValueEntryV2Response =
  experimental_Brands.UpdateBrandKitSectionFieldValueEntryV2Response;

type UpdateBrandKitSectionFieldValueEntryV2Data =
  experimental_Brands.UpdateBrandKitSectionFieldValueEntryV2Data;

type GetBrandKitSectionFieldValueEntryV2Error =
  experimental_Brands.GetBrandKitSectionFieldValueEntryV2Error;

type GetBrandKitSectionFieldValueEntryV2Response =
  experimental_Brands.GetBrandKitSectionFieldValueEntryV2Response;

type GetBrandKitSectionFieldValueEntryV2Data =
  experimental_Brands.GetBrandKitSectionFieldValueEntryV2Data;

type CreateBrandKitSectionFieldValueEntryV2Error =
  experimental_Brands.CreateBrandKitSectionFieldValueEntryV2Error;

type CreateBrandKitSectionFieldValueEntryV2Response =
  experimental_Brands.CreateBrandKitSectionFieldValueEntryV2Response;

type CreateBrandKitSectionFieldValueEntryV2Data =
  experimental_Brands.CreateBrandKitSectionFieldValueEntryV2Data;

type UpdateBrandKitSectionFieldValueEntryError =
  experimental_Brands.UpdateBrandKitSectionFieldValueEntryError;

type UpdateBrandKitSectionFieldValueEntryResponse =
  experimental_Brands.UpdateBrandKitSectionFieldValueEntryResponse;

type UpdateBrandKitSectionFieldValueEntryData =
  experimental_Brands.UpdateBrandKitSectionFieldValueEntryData;

type GetBrandKitSectionFieldValueEntryError =
  experimental_Brands.GetBrandKitSectionFieldValueEntryError;

type GetBrandKitSectionFieldValueEntryResponse =
  experimental_Brands.GetBrandKitSectionFieldValueEntryResponse;

type GetBrandKitSectionFieldValueEntryData =
  experimental_Brands.GetBrandKitSectionFieldValueEntryData;

type DeleteBrandKitSectionFieldValueEntryError =
  experimental_Brands.DeleteBrandKitSectionFieldValueEntryError;

type DeleteBrandKitSectionFieldValueEntryResponse =
  experimental_Brands.DeleteBrandKitSectionFieldValueEntryResponse;

type DeleteBrandKitSectionFieldValueEntryData =
  experimental_Brands.DeleteBrandKitSectionFieldValueEntryData;

type CreateBrandKitSectionFieldValueEntryError =
  experimental_Brands.CreateBrandKitSectionFieldValueEntryError;

type CreateBrandKitSectionFieldValueEntryResponse =
  experimental_Brands.CreateBrandKitSectionFieldValueEntryResponse;

type CreateBrandKitSectionFieldValueEntryData =
  experimental_Brands.CreateBrandKitSectionFieldValueEntryData;

type GetBrandKitSectionFieldReferenceError =
  experimental_Brands.GetBrandKitSectionFieldReferenceError;

type GetBrandKitSectionFieldReferenceResponse =
  experimental_Brands.GetBrandKitSectionFieldReferenceResponse;

type GetBrandKitSectionFieldReferenceData =
  experimental_Brands.GetBrandKitSectionFieldReferenceData;

type DeleteBrandKitSectonFieldReferenceError =
  experimental_Brands.DeleteBrandKitSectonFieldReferenceError;

type DeleteBrandKitSectonFieldReferenceResponse =
  experimental_Brands.DeleteBrandKitSectonFieldReferenceResponse;

type DeleteBrandKitSectonFieldReferenceData =
  experimental_Brands.DeleteBrandKitSectonFieldReferenceData;

type CreateBrandKitSectionFieldReferenceError =
  experimental_Brands.CreateBrandKitSectionFieldReferenceError;

type CreateBrandKitSectionFieldReferenceData =
  experimental_Brands.CreateBrandKitSectionFieldReferenceData;

type ListBrandKitSectionFieldReferencesError =
  experimental_Brands.ListBrandKitSectionFieldReferencesError;

type ListBrandKitSectionFieldReferencesResponse =
  experimental_Brands.ListBrandKitSectionFieldReferencesResponse;

type ListBrandKitSectionFieldReferencesData =
  experimental_Brands.ListBrandKitSectionFieldReferencesData;

type UpdateBrandKitSectionFieldV2Error = experimental_Brands.UpdateBrandKitSectionFieldV2Error;

type UpdateBrandKitSectionFieldV2Response =
  experimental_Brands.UpdateBrandKitSectionFieldV2Response;

type UpdateBrandKitSectionFieldV2Data = experimental_Brands.UpdateBrandKitSectionFieldV2Data;

type GetBrandKitSectionFieldV2Error = experimental_Brands.GetBrandKitSectionFieldV2Error;

type GetBrandKitSectionFieldV2Response = experimental_Brands.GetBrandKitSectionFieldV2Response;

type GetBrandKitSectionFieldV2Data = experimental_Brands.GetBrandKitSectionFieldV2Data;

type GetBrandKitSectionFieldAdminError = experimental_Brands.GetBrandKitSectionFieldAdminError;

type GetBrandKitSectionFieldAdminResponse =
  experimental_Brands.GetBrandKitSectionFieldAdminResponse;

type GetBrandKitSectionFieldAdminData = experimental_Brands.GetBrandKitSectionFieldAdminData;

type UpdateBrandKitSectionFieldError = experimental_Brands.UpdateBrandKitSectionFieldError;

type UpdateBrandKitSectionFieldResponse = experimental_Brands.UpdateBrandKitSectionFieldResponse;

type UpdateBrandKitSectionFieldData = experimental_Brands.UpdateBrandKitSectionFieldData;

type GetBrandKitSectionFieldError = experimental_Brands.GetBrandKitSectionFieldError;

type GetBrandKitSectionFieldResponse = experimental_Brands.GetBrandKitSectionFieldResponse;

type GetBrandKitSectionFieldData = experimental_Brands.GetBrandKitSectionFieldData;

type DeleteBrandKitSectionFieldError = experimental_Brands.DeleteBrandKitSectionFieldError;

type DeleteBrandKitSectionFieldResponse = experimental_Brands.DeleteBrandKitSectionFieldResponse;

type DeleteBrandKitSectionFieldData = experimental_Brands.DeleteBrandKitSectionFieldData;

type ListBrandKitSectionFieldsAdminError = experimental_Brands.ListBrandKitSectionFieldsAdminError;

type ListBrandKitSectionFieldsAdminResponse =
  experimental_Brands.ListBrandKitSectionFieldsAdminResponse;

type ListBrandKitSectionFieldsAdminData = experimental_Brands.ListBrandKitSectionFieldsAdminData;

type ListBrandKitSectionFieldsV3Error = experimental_Brands.ListBrandKitSectionFieldsV3Error;

type ListBrandKitSectionFieldsV3Response = experimental_Brands.ListBrandKitSectionFieldsV3Response;

type ListBrandKitSectionFieldsV3Data = experimental_Brands.ListBrandKitSectionFieldsV3Data;

type CreateBrandKitSectionFieldV2Error = experimental_Brands.CreateBrandKitSectionFieldV2Error;

type CreateBrandKitSectionFieldV2Response =
  experimental_Brands.CreateBrandKitSectionFieldV2Response;

type CreateBrandKitSectionFieldV2Data = experimental_Brands.CreateBrandKitSectionFieldV2Data;

type ListBrandKitSectionFieldsV2Error = experimental_Brands.ListBrandKitSectionFieldsV2Error;

type ListBrandKitSectionFieldsV2Response = experimental_Brands.ListBrandKitSectionFieldsV2Response;

type ListBrandKitSectionFieldsV2Data = experimental_Brands.ListBrandKitSectionFieldsV2Data;

type CreateBrandKitSectionFieldError = experimental_Brands.CreateBrandKitSectionFieldError;

type CreateBrandKitSectionFieldResponse = experimental_Brands.CreateBrandKitSectionFieldResponse;

type CreateBrandKitSectionFieldData = experimental_Brands.CreateBrandKitSectionFieldData;

type ListBrandKitSectionFieldsError = experimental_Brands.ListBrandKitSectionFieldsError;

type ListBrandKitSectionFieldsResponse = experimental_Brands.ListBrandKitSectionFieldsResponse;

type ListBrandKitSectionFieldsData = experimental_Brands.ListBrandKitSectionFieldsData;

type GetBrandKitSectionAdminError = experimental_Brands.GetBrandKitSectionAdminError;

type GetBrandKitSectionAdminResponse = experimental_Brands.GetBrandKitSectionAdminResponse;

type GetBrandKitSectionAdminData = experimental_Brands.GetBrandKitSectionAdminData;

type UpdateBrandKitSectionError = experimental_Brands.UpdateBrandKitSectionError;

type UpdateBrandKitSectionResponse = experimental_Brands.UpdateBrandKitSectionResponse;

type UpdateBrandKitSectionData = experimental_Brands.UpdateBrandKitSectionData;

type GetBrandKitSectionError = experimental_Brands.GetBrandKitSectionError;

type GetBrandKitSectionResponse = experimental_Brands.GetBrandKitSectionResponse;

type GetBrandKitSectionData = experimental_Brands.GetBrandKitSectionData;

type DeleteBrandKitSectionError = experimental_Brands.DeleteBrandKitSectionError;

type DeleteBrandKitSectionResponse = experimental_Brands.DeleteBrandKitSectionResponse;

type DeleteBrandKitSectionData = experimental_Brands.DeleteBrandKitSectionData;

type ListBrandKitSectionsAdminError = experimental_Brands.ListBrandKitSectionsAdminError;

type ListBrandKitSectionsAdminResponse = experimental_Brands.ListBrandKitSectionsAdminResponse;

type ListBrandKitSectionsAdminData = experimental_Brands.ListBrandKitSectionsAdminData;

type CreateBrandKitSectionError = experimental_Brands.CreateBrandKitSectionError;

type CreateBrandKitSectionData = experimental_Brands.CreateBrandKitSectionData;

type ListBrandKitSectionsError = experimental_Brands.ListBrandKitSectionsError;

type ListBrandKitSectionsResponse = experimental_Brands.ListBrandKitSectionsResponse;

type ListBrandKitSectionsData = experimental_Brands.ListBrandKitSectionsData;

type GetBrandKitReferenceError = experimental_Brands.GetBrandKitReferenceError;

type GetBrandKitReferenceResponse = experimental_Brands.GetBrandKitReferenceResponse;

type GetBrandKitReferenceData = experimental_Brands.GetBrandKitReferenceData;

type DeleteBrandKitReferenceError = experimental_Brands.DeleteBrandKitReferenceError;

type DeleteBrandKitReferenceResponse = experimental_Brands.DeleteBrandKitReferenceResponse;

type DeleteBrandKitReferenceData = experimental_Brands.DeleteBrandKitReferenceData;

type CreateBrandKitReferenceError = experimental_Brands.CreateBrandKitReferenceError;

type CreateBrandKitReferenceData = experimental_Brands.CreateBrandKitReferenceData;

type ListBrandKitReferencesError = experimental_Brands.ListBrandKitReferencesError;

type ListBrandKitReferencesResponse = experimental_Brands.ListBrandKitReferencesResponse;

type ListBrandKitReferencesData = experimental_Brands.ListBrandKitReferencesData;

type UpdateBrandKitError = experimental_Brands.UpdateBrandKitError;

type UpdateBrandKitData = experimental_Brands.UpdateBrandKitData;

type GetBrandKitError = experimental_Brands.GetBrandKitError;

type GetBrandKitResponse = experimental_Brands.GetBrandKitResponse;

type GetBrandKitData = experimental_Brands.GetBrandKitData;

type DeleteBrandKitError = experimental_Brands.DeleteBrandKitError;

type DeleteBrandKitResponse = experimental_Brands.DeleteBrandKitResponse;

type DeleteBrandKitData = experimental_Brands.DeleteBrandKitData;

type CreateBrandKitError = experimental_Brands.CreateBrandKitError;

type CreateBrandKitResponse = experimental_Brands.CreateBrandKitResponse;

type CreateBrandKitData = experimental_Brands.CreateBrandKitData;

type ListBrandKitsError = experimental_Brands.ListBrandKitsError;

type ListBrandKitsResponse = experimental_Brands.ListBrandKitsResponse;

type ListBrandKitsData = experimental_Brands.ListBrandKitsData;

type GetVersionData = experimental_Brands.GetVersionData;

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get Version
 */
export const getVersion = <ThrowOnError extends boolean = false>(
  options?: Options<GetVersionData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
    url: '/api/version',
    ...options,
  });
};

/**
 * List Brand Kits
 */
export const listBrandKits = <ThrowOnError extends boolean = false>(
  options: Options<ListBrandKitsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListBrandKitsResponse,
    ListBrandKitsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits',
    ...options,
  });
};

/**
 * Create Brand Kit
 */
export const createBrandKit = <ThrowOnError extends boolean = false>(
  options: Options<CreateBrandKitData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateBrandKitResponse,
    CreateBrandKitError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete Brand Kit
 */
export const deleteBrandKit = <ThrowOnError extends boolean = false>(
  options: Options<DeleteBrandKitData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteBrandKitResponse,
    DeleteBrandKitError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}',
    ...options,
  });
};

/**
 * Get Brand Kit
 */
export const getBrandKit = <ThrowOnError extends boolean = false>(
  options: Options<GetBrandKitData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetBrandKitResponse, GetBrandKitError, ThrowOnError>(
    {
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}',
      ...options,
    },
  );
};

/**
 * Update Brand Kit
 */
export const updateBrandKit = <ThrowOnError extends boolean = false>(
  options: Options<UpdateBrandKitData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<unknown, UpdateBrandKitError, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * List Brand Kit References
 */
export const listBrandKitReferences = <ThrowOnError extends boolean = false>(
  options: Options<ListBrandKitReferencesData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListBrandKitReferencesResponse,
    ListBrandKitReferencesError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/references',
    ...options,
  });
};

/**
 * Create Brand Kit Reference
 */
export const createBrandKitReference = <ThrowOnError extends boolean = false>(
  options: Options<CreateBrandKitReferenceData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    unknown,
    CreateBrandKitReferenceError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/references',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete Brand Kit Reference
 */
export const deleteBrandKitReference = <ThrowOnError extends boolean = false>(
  options: Options<DeleteBrandKitReferenceData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteBrandKitReferenceResponse,
    DeleteBrandKitReferenceError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/references/{referenceId}',
    ...options,
  });
};

/**
 * Get Brand Kit Reference
 */
export const getBrandKitReference = <ThrowOnError extends boolean = false>(
  options: Options<GetBrandKitReferenceData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetBrandKitReferenceResponse,
    GetBrandKitReferenceError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/references/{referenceId}',
    ...options,
  });
};

/**
 * List Brand Kit Sections
 */
export const listBrandKitSections = <ThrowOnError extends boolean = false>(
  options: Options<ListBrandKitSectionsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListBrandKitSectionsResponse,
    ListBrandKitSectionsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections',
    ...options,
  });
};

/**
 * Create Brand Kit Section
 */
export const createBrandKitSection = <ThrowOnError extends boolean = false>(
  options: Options<CreateBrandKitSectionData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<unknown, CreateBrandKitSectionError, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * List Brand Kit Sections Admin
 */
export const listBrandKitSectionsAdmin = <ThrowOnError extends boolean = false>(
  options: Options<ListBrandKitSectionsAdminData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListBrandKitSectionsAdminResponse,
    ListBrandKitSectionsAdminError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/admin/v1/brandkits/{brandkitId}/sections',
    ...options,
  });
};

/**
 * Delete Brand Kit Section
 */
export const deleteBrandKitSection = <ThrowOnError extends boolean = false>(
  options: Options<DeleteBrandKitSectionData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteBrandKitSectionResponse,
    DeleteBrandKitSectionError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}',
    ...options,
  });
};

/**
 * Get Brand Kit Section
 */
export const getBrandKitSection = <ThrowOnError extends boolean = false>(
  options: Options<GetBrandKitSectionData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetBrandKitSectionResponse,
    GetBrandKitSectionError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}',
    ...options,
  });
};

/**
 * Update Brand Kit Section
 */
export const updateBrandKitSection = <ThrowOnError extends boolean = false>(
  options: Options<UpdateBrandKitSectionData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateBrandKitSectionResponse,
    UpdateBrandKitSectionError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Get Brand Kit Section Admin
 */
export const getBrandKitSectionAdmin = <ThrowOnError extends boolean = false>(
  options: Options<GetBrandKitSectionAdminData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetBrandKitSectionAdminResponse,
    GetBrandKitSectionAdminError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/admin/v1/brandkits/{brandkitId}/sections/{sectionId}',
    ...options,
  });
};

/**
 * @deprecated
 * List Brand Kit Section Fields
 */
export const listBrandKitSectionFields = <ThrowOnError extends boolean = false>(
  options: Options<ListBrandKitSectionFieldsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListBrandKitSectionFieldsResponse,
    ListBrandKitSectionFieldsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields',
    ...options,
  });
};

/**
 * @deprecated
 * Create Brand Kit Section Field
 */
export const createBrandKitSectionField = <ThrowOnError extends boolean = false>(
  options: Options<CreateBrandKitSectionFieldData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateBrandKitSectionFieldResponse,
    CreateBrandKitSectionFieldError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * List Brand Kit Section Fields
 */
export const listBrandKitSectionFieldsV2 = <ThrowOnError extends boolean = false>(
  options: Options<ListBrandKitSectionFieldsV2Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListBrandKitSectionFieldsV2Response,
    ListBrandKitSectionFieldsV2Error,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields',
    ...options,
  });
};

/**
 * Create Brand Kit Section Field
 */
export const createBrandKitSectionFieldV2 = <ThrowOnError extends boolean = false>(
  options: Options<CreateBrandKitSectionFieldV2Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateBrandKitSectionFieldV2Response,
    CreateBrandKitSectionFieldV2Error,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * List Brand Kit Section Fields
 * List all fields belonging to a brand kit section with pagination.
 *
 * Retrieves a paginated list of fields for the specified section within a brand kit,
 * performing an in-memory join of any associated reference data.
 *
 * Args:
 *
 * - request: The incoming HTTP request.
 * - organizationId: The unique identifier of the organization.
 * - brandkitId: The unique identifier of the brand kit.
 * - sectionId: The unique identifier of the section whose fields are being listed.
 * - pageNumber: The 1-based page number to retrieve. Defaults to 1. Minimum value is 1.
 * - pageSize: The number of results per page (max 100). Defaults to 50. Minimum value is 1.
 *
 * Returns:
 *
 * - ListBrandKitSectionFieldsModelResponse_v3: Paginated response containing the total count, page metadata, and the list of section field objects.
 */
export const listBrandKitSectionFieldsV3 = <ThrowOnError extends boolean = false>(
  options: Options<ListBrandKitSectionFieldsV3Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListBrandKitSectionFieldsV3Response,
    ListBrandKitSectionFieldsV3Error,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v3/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields',
    ...options,
  });
};

/**
 * List Brand Kit Section Fields Admin
 */
export const listBrandKitSectionFieldsAdmin = <ThrowOnError extends boolean = false>(
  options: Options<ListBrandKitSectionFieldsAdminData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListBrandKitSectionFieldsAdminResponse,
    ListBrandKitSectionFieldsAdminError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/admin/v1/brandkits/{brandkitId}/sections/{sectionId}/fields',
    ...options,
  });
};

/**
 * Delete Brand Kit Section Field
 */
export const deleteBrandKitSectionField = <ThrowOnError extends boolean = false>(
  options: Options<DeleteBrandKitSectionFieldData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteBrandKitSectionFieldResponse,
    DeleteBrandKitSectionFieldError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}',
    ...options,
  });
};

/**
 * @deprecated
 * Get Brand Kit Section Field
 */
export const getBrandKitSectionField = <ThrowOnError extends boolean = false>(
  options: Options<GetBrandKitSectionFieldData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetBrandKitSectionFieldResponse,
    GetBrandKitSectionFieldError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}',
    ...options,
  });
};

/**
 * @deprecated
 * Update Brand Kit Section Field
 */
export const updateBrandKitSectionField = <ThrowOnError extends boolean = false>(
  options: Options<UpdateBrandKitSectionFieldData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateBrandKitSectionFieldResponse,
    UpdateBrandKitSectionFieldError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Get Brand Kit Section Field Admin
 */
export const getBrandKitSectionFieldAdmin = <ThrowOnError extends boolean = false>(
  options: Options<GetBrandKitSectionFieldAdminData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetBrandKitSectionFieldAdminResponse,
    GetBrandKitSectionFieldAdminError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/admin/v1/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}',
    ...options,
  });
};

/**
 * Get Brand Kit Section Field
 */
export const getBrandKitSectionFieldV2 = <ThrowOnError extends boolean = false>(
  options: Options<GetBrandKitSectionFieldV2Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetBrandKitSectionFieldV2Response,
    GetBrandKitSectionFieldV2Error,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}',
    ...options,
  });
};

/**
 * Update Brand Kit Section Field
 */
export const updateBrandKitSectionFieldV2 = <ThrowOnError extends boolean = false>(
  options: Options<UpdateBrandKitSectionFieldV2Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateBrandKitSectionFieldV2Response,
    UpdateBrandKitSectionFieldV2Error,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * List Brand Kit Section Field References
 */
export const listBrandKitSectionFieldReferences = <ThrowOnError extends boolean = false>(
  options: Options<ListBrandKitSectionFieldReferencesData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListBrandKitSectionFieldReferencesResponse,
    ListBrandKitSectionFieldReferencesError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/references',
    ...options,
  });
};

/**
 * Create Brand Kit Section Field Reference
 */
export const createBrandKitSectionFieldReference = <ThrowOnError extends boolean = false>(
  options: Options<CreateBrandKitSectionFieldReferenceData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    unknown,
    CreateBrandKitSectionFieldReferenceError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/references',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete Brand Kit Secton Field Reference
 */
export const deleteBrandKitSectonFieldReference = <ThrowOnError extends boolean = false>(
  options: Options<DeleteBrandKitSectonFieldReferenceData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteBrandKitSectonFieldReferenceResponse,
    DeleteBrandKitSectonFieldReferenceError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/references/{referenceId}',
    ...options,
  });
};

/**
 * Get Brand Kit Section Field Reference
 */
export const getBrandKitSectionFieldReference = <ThrowOnError extends boolean = false>(
  options: Options<GetBrandKitSectionFieldReferenceData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetBrandKitSectionFieldReferenceResponse,
    GetBrandKitSectionFieldReferenceError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/references/{referenceId}',
    ...options,
  });
};

/**
 * Create Brand Kit Section Field Value Entry
 */
export const createBrandKitSectionFieldValueEntry = <ThrowOnError extends boolean = false>(
  options: Options<CreateBrandKitSectionFieldValueEntryData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateBrandKitSectionFieldValueEntryResponse,
    CreateBrandKitSectionFieldValueEntryError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/values',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete Brand Kit Section Field Value Entry
 */
export const deleteBrandKitSectionFieldValueEntry = <ThrowOnError extends boolean = false>(
  options: Options<DeleteBrandKitSectionFieldValueEntryData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteBrandKitSectionFieldValueEntryResponse,
    DeleteBrandKitSectionFieldValueEntryError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/values/{entryId}',
    ...options,
  });
};

/**
 * Get Brand Kit Section Field Value Entry
 */
export const getBrandKitSectionFieldValueEntry = <ThrowOnError extends boolean = false>(
  options: Options<GetBrandKitSectionFieldValueEntryData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetBrandKitSectionFieldValueEntryResponse,
    GetBrandKitSectionFieldValueEntryError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/values/{entryId}',
    ...options,
  });
};

/**
 * Update Brand Kit Section Field Value Entry
 */
export const updateBrandKitSectionFieldValueEntry = <ThrowOnError extends boolean = false>(
  options: Options<UpdateBrandKitSectionFieldValueEntryData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateBrandKitSectionFieldValueEntryResponse,
    UpdateBrandKitSectionFieldValueEntryError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v1/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/values/{valueEntryId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Create Brand Kit Section Field Value Entry V2
 */
export const createBrandKitSectionFieldValueEntryV2 = <ThrowOnError extends boolean = false>(
  options: Options<CreateBrandKitSectionFieldValueEntryV2Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateBrandKitSectionFieldValueEntryV2Response,
    CreateBrandKitSectionFieldValueEntryV2Error,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/values',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Get Brand Kit Section Field Value Entry V2
 */
export const getBrandKitSectionFieldValueEntryV2 = <ThrowOnError extends boolean = false>(
  options: Options<GetBrandKitSectionFieldValueEntryV2Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetBrandKitSectionFieldValueEntryV2Response,
    GetBrandKitSectionFieldValueEntryV2Error,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/values/{valueEntryId}',
    ...options,
  });
};

/**
 * Update Brand Kit Section Field Value Entry V2
 */
export const updateBrandKitSectionFieldValueEntryV2 = <ThrowOnError extends boolean = false>(
  options: Options<UpdateBrandKitSectionFieldValueEntryV2Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateBrandKitSectionFieldValueEntryV2Response,
    UpdateBrandKitSectionFieldValueEntryV2Error,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/values/{valueEntryId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Get Public Openapi
 * Generate public OpenAPI documentation that only includes routes tagged as 'public'.
 */
export const getPublicOpenapi = <ThrowOnError extends boolean = false>(
  options?: Options<GetPublicOpenapiData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
    url: '/api/docs/openapi.json',
    ...options,
  });
};

/**
 * Get Public Swagger Ui
 * Generate Swagger UI HTML page for public OpenAPI documentation.
 */
export const getPublicSwaggerUi = <ThrowOnError extends boolean = false>(
  options?: Options<GetPublicSwaggerUiData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetPublicSwaggerUiResponse, unknown, ThrowOnError>({
    url: '/api/docs',
    ...options,
  });
};

/**
 * Get Public Redoc Ui
 * Generate ReDoc HTML page for public OpenAPI documentation.
 */
export const getPublicRedocUi = <ThrowOnError extends boolean = false>(
  options?: Options<GetPublicRedocUiData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetPublicRedocUiResponse, unknown, ThrowOnError>({
    url: '/api/docs/redoc',
    ...options,
  });
};
