// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { experimental_Brands } from './types.gen';
import { client as _heyApiClient } from './client.gen';

type GetPublicRedocUiResponse = experimental_Brands.GetPublicRedocUiResponse;

type GetPublicRedocUiData = experimental_Brands.GetPublicRedocUiData;

type GetPublicSwaggerUiResponse = experimental_Brands.GetPublicSwaggerUiResponse;

type GetPublicSwaggerUiData = experimental_Brands.GetPublicSwaggerUiData;

type GetPublicOpenapiData = experimental_Brands.GetPublicOpenapiData;

type UpdateBrandKitSectionFieldValueEntryV2Error =
  experimental_Brands.UpdateBrandKitSectionFieldValueEntryV2Error;

type UpdateBrandKitSectionFieldValueEntryV2Response =
  experimental_Brands.UpdateBrandKitSectionFieldValueEntryV2Response;

type UpdateBrandKitSectionFieldValueEntryV2Data =
  experimental_Brands.UpdateBrandKitSectionFieldValueEntryV2Data;

type GetBrandKitSectionFieldValueEntryV2Error =
  experimental_Brands.GetBrandKitSectionFieldValueEntryV2Error;

type GetBrandKitSectionFieldValueEntryV2Response =
  experimental_Brands.GetBrandKitSectionFieldValueEntryV2Response;

type GetBrandKitSectionFieldValueEntryV2Data =
  experimental_Brands.GetBrandKitSectionFieldValueEntryV2Data;

type CreateBrandKitSectionFieldValueEntryV2Error =
  experimental_Brands.CreateBrandKitSectionFieldValueEntryV2Error;

type CreateBrandKitSectionFieldValueEntryV2Response =
  experimental_Brands.CreateBrandKitSectionFieldValueEntryV2Response;

type CreateBrandKitSectionFieldValueEntryV2Data =
  experimental_Brands.CreateBrandKitSectionFieldValueEntryV2Data;

type UpdateBrandKitSectionFieldError = experimental_Brands.UpdateBrandKitSectionFieldError;

type UpdateBrandKitSectionFieldResponse = experimental_Brands.UpdateBrandKitSectionFieldResponse;

type UpdateBrandKitSectionFieldData = experimental_Brands.UpdateBrandKitSectionFieldData;

type GetBrandKitSectionFieldError = experimental_Brands.GetBrandKitSectionFieldError;

type GetBrandKitSectionFieldResponse = experimental_Brands.GetBrandKitSectionFieldResponse;

type GetBrandKitSectionFieldData = experimental_Brands.GetBrandKitSectionFieldData;

type GetBrandKitSectionFieldAdminError = experimental_Brands.GetBrandKitSectionFieldAdminError;

type GetBrandKitSectionFieldAdminResponse =
  experimental_Brands.GetBrandKitSectionFieldAdminResponse;

type GetBrandKitSectionFieldAdminData = experimental_Brands.GetBrandKitSectionFieldAdminData;

type ListBrandKitSectionFieldsAdminError = experimental_Brands.ListBrandKitSectionFieldsAdminError;

type ListBrandKitSectionFieldsAdminResponse =
  experimental_Brands.ListBrandKitSectionFieldsAdminResponse;

type ListBrandKitSectionFieldsAdminData = experimental_Brands.ListBrandKitSectionFieldsAdminData;

type ListBrandKitSectionFieldsV3Error = experimental_Brands.ListBrandKitSectionFieldsV3Error;

type ListBrandKitSectionFieldsV3Response = experimental_Brands.ListBrandKitSectionFieldsV3Response;

type ListBrandKitSectionFieldsV3Data = experimental_Brands.ListBrandKitSectionFieldsV3Data;

type CreateBrandKitSectionFieldError = experimental_Brands.CreateBrandKitSectionFieldError;

type CreateBrandKitSectionFieldResponse = experimental_Brands.CreateBrandKitSectionFieldResponse;

type CreateBrandKitSectionFieldData = experimental_Brands.CreateBrandKitSectionFieldData;

type ListBrandKitSectionFieldsError = experimental_Brands.ListBrandKitSectionFieldsError;

type ListBrandKitSectionFieldsResponse = experimental_Brands.ListBrandKitSectionFieldsResponse;

type ListBrandKitSectionFieldsData = experimental_Brands.ListBrandKitSectionFieldsData;

type GetBrandKitSectionAdminError = experimental_Brands.GetBrandKitSectionAdminError;

type GetBrandKitSectionAdminResponse = experimental_Brands.GetBrandKitSectionAdminResponse;

type GetBrandKitSectionAdminData = experimental_Brands.GetBrandKitSectionAdminData;

type ListBrandKitSectionsAdminError = experimental_Brands.ListBrandKitSectionsAdminError;

type ListBrandKitSectionsAdminResponse = experimental_Brands.ListBrandKitSectionsAdminResponse;

type ListBrandKitSectionsAdminData = experimental_Brands.ListBrandKitSectionsAdminData;

type GetVersionData = experimental_Brands.GetVersionData;

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get Version
 */
export const getVersion = <ThrowOnError extends boolean = false>(
  options?: Options<GetVersionData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
    url: '/api/version',
    ...options,
  });
};

/**
 * List Brand Kit Sections Admin
 */
export const listBrandKitSectionsAdmin = <ThrowOnError extends boolean = false>(
  options: Options<ListBrandKitSectionsAdminData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListBrandKitSectionsAdminResponse,
    ListBrandKitSectionsAdminError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/admin/v1/brandkits/{brandkitId}/sections',
    ...options,
  });
};

/**
 * Get Brand Kit Section Admin
 */
export const getBrandKitSectionAdmin = <ThrowOnError extends boolean = false>(
  options: Options<GetBrandKitSectionAdminData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetBrandKitSectionAdminResponse,
    GetBrandKitSectionAdminError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/admin/v1/brandkits/{brandkitId}/sections/{sectionId}',
    ...options,
  });
};

/**
 * List Brand Kit Section Fields
 */
export const listBrandKitSectionFields = <ThrowOnError extends boolean = false>(
  options: Options<ListBrandKitSectionFieldsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListBrandKitSectionFieldsResponse,
    ListBrandKitSectionFieldsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields',
    ...options,
  });
};

/**
 * Create Brand Kit Section Field
 */
export const createBrandKitSectionField = <ThrowOnError extends boolean = false>(
  options: Options<CreateBrandKitSectionFieldData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateBrandKitSectionFieldResponse,
    CreateBrandKitSectionFieldError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * List Brand Kit Section Fields
 * List all fields belonging to a brand kit section with pagination.
 *
 * Retrieves a paginated list of fields for the specified section within a brand kit,
 * performing an in-memory join of any associated reference data.
 *
 * Args:
 *
 * - request: The incoming HTTP request.
 * - organizationId: The unique identifier of the organization.
 * - brandkitId: The unique identifier of the brand kit.
 * - sectionId: The unique identifier of the section whose fields are being listed.
 * - pageNumber: The 1-based page number to retrieve. Defaults to 1. Minimum value is 1.
 * - pageSize: The number of results per page (max 100). Defaults to 50. Minimum value is 1.
 *
 * Returns:
 *
 * - ListBrandKitSectionFieldsModelResponse_v3: Paginated response containing the total count, page metadata, and the list of section field objects.
 */
export const listBrandKitSectionFieldsV3 = <ThrowOnError extends boolean = false>(
  options: Options<ListBrandKitSectionFieldsV3Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListBrandKitSectionFieldsV3Response,
    ListBrandKitSectionFieldsV3Error,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v3/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields',
    ...options,
  });
};

/**
 * List Brand Kit Section Fields Admin
 */
export const listBrandKitSectionFieldsAdmin = <ThrowOnError extends boolean = false>(
  options: Options<ListBrandKitSectionFieldsAdminData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListBrandKitSectionFieldsAdminResponse,
    ListBrandKitSectionFieldsAdminError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/admin/v1/brandkits/{brandkitId}/sections/{sectionId}/fields',
    ...options,
  });
};

/**
 * Get Brand Kit Section Field Admin
 */
export const getBrandKitSectionFieldAdmin = <ThrowOnError extends boolean = false>(
  options: Options<GetBrandKitSectionFieldAdminData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetBrandKitSectionFieldAdminResponse,
    GetBrandKitSectionFieldAdminError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/admin/v1/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}',
    ...options,
  });
};

/**
 * Get Brand Kit Section Field
 */
export const getBrandKitSectionField = <ThrowOnError extends boolean = false>(
  options: Options<GetBrandKitSectionFieldData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetBrandKitSectionFieldResponse,
    GetBrandKitSectionFieldError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}',
    ...options,
  });
};

/**
 * Update Brand Kit Section Field
 */
export const updateBrandKitSectionField = <ThrowOnError extends boolean = false>(
  options: Options<UpdateBrandKitSectionFieldData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateBrandKitSectionFieldResponse,
    UpdateBrandKitSectionFieldError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Create Brand Kit Section Field Value Entry V2
 */
export const createBrandKitSectionFieldValueEntryV2 = <ThrowOnError extends boolean = false>(
  options: Options<CreateBrandKitSectionFieldValueEntryV2Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateBrandKitSectionFieldValueEntryV2Response,
    CreateBrandKitSectionFieldValueEntryV2Error,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/values',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Get Brand Kit Section Field Value Entry V2
 */
export const getBrandKitSectionFieldValueEntryV2 = <ThrowOnError extends boolean = false>(
  options: Options<GetBrandKitSectionFieldValueEntryV2Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetBrandKitSectionFieldValueEntryV2Response,
    GetBrandKitSectionFieldValueEntryV2Error,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/values/{valueEntryId}',
    ...options,
  });
};

/**
 * Update Brand Kit Section Field Value Entry V2
 */
export const updateBrandKitSectionFieldValueEntryV2 = <ThrowOnError extends boolean = false>(
  options: Options<UpdateBrandKitSectionFieldValueEntryV2Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateBrandKitSectionFieldValueEntryV2Response,
    UpdateBrandKitSectionFieldValueEntryV2Error,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/brands/v2/organizations/{organizationId}/brandkits/{brandkitId}/sections/{sectionId}/fields/{fieldId}/values/{valueEntryId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Get Public Openapi
 * Generate public OpenAPI documentation that only includes routes tagged as 'public'.
 */
export const getPublicOpenapi = <ThrowOnError extends boolean = false>(
  options?: Options<GetPublicOpenapiData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
    url: '/api/docs/openapi.json',
    ...options,
  });
};

/**
 * Get Public Swagger Ui
 * Generate Swagger UI HTML page for public OpenAPI documentation.
 */
export const getPublicSwaggerUi = <ThrowOnError extends boolean = false>(
  options?: Options<GetPublicSwaggerUiData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetPublicSwaggerUiResponse, unknown, ThrowOnError>({
    url: '/api/docs',
    ...options,
  });
};

/**
 * Get Public Redoc Ui
 * Generate ReDoc HTML page for public OpenAPI documentation.
 */
export const getPublicRedocUi = <ThrowOnError extends boolean = false>(
  options?: Options<GetPublicRedocUiData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetPublicRedocUiResponse, unknown, ThrowOnError>({
    url: '/api/docs/redoc',
    ...options,
  });
};
