// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type TDataShape,
  type Client,
  formDataBodySerializer,
} from '@hey-api/client-fetch';
import type { experimental_Documents } from './types.gen';
import { client as _heyApiClient } from './client.gen';

type GetPublicRedocUiResponse = experimental_Documents.GetPublicRedocUiResponse;

type GetPublicRedocUiData = experimental_Documents.GetPublicRedocUiData;

type GetPublicSwaggerUiResponse = experimental_Documents.GetPublicSwaggerUiResponse;

type GetPublicSwaggerUiData = experimental_Documents.GetPublicSwaggerUiData;

type GetPublicOpenapiData = experimental_Documents.GetPublicOpenapiData;

type ListChunksAdminError = experimental_Documents.ListChunksAdminError;

type ListChunksAdminResponse = experimental_Documents.ListChunksAdminResponse;

type ListChunksAdminData = experimental_Documents.ListChunksAdminData;

type GetFileV2Error = experimental_Documents.GetFileV2Error;

type GetFileV2Data = experimental_Documents.GetFileV2Data;

type GetChunkFileV2Error = experimental_Documents.GetChunkFileV2Error;

type GetChunkFileV2Data = experimental_Documents.GetChunkFileV2Data;

type GetChunkFieldError = experimental_Documents.GetChunkFieldError;

type GetChunkFieldResponse = experimental_Documents.GetChunkFieldResponse;

type GetChunkFieldData = experimental_Documents.GetChunkFieldData;

type DeleteChunkFieldError = experimental_Documents.DeleteChunkFieldError;

type DeleteChunkFieldResponse = experimental_Documents.DeleteChunkFieldResponse;

type DeleteChunkFieldData = experimental_Documents.DeleteChunkFieldData;

type CreateChunkFieldError = experimental_Documents.CreateChunkFieldError;

type CreateChunkFieldResponse = experimental_Documents.CreateChunkFieldResponse;

type CreateChunkFieldData = experimental_Documents.CreateChunkFieldData;

type ListChunkFieldsError = experimental_Documents.ListChunkFieldsError;

type ListChunkFieldsResponse = experimental_Documents.ListChunkFieldsResponse;

type ListChunkFieldsData = experimental_Documents.ListChunkFieldsData;

type UpdateChunkTopicError = experimental_Documents.UpdateChunkTopicError;

type UpdateChunkTopicResponse = experimental_Documents.UpdateChunkTopicResponse;

type UpdateChunkTopicData = experimental_Documents.UpdateChunkTopicData;

type GetChunkTopicError = experimental_Documents.GetChunkTopicError;

type GetChunkTopicResponse = experimental_Documents.GetChunkTopicResponse;

type GetChunkTopicData = experimental_Documents.GetChunkTopicData;

type DeleteChunkTopicError = experimental_Documents.DeleteChunkTopicError;

type DeleteChunkTopicResponse = experimental_Documents.DeleteChunkTopicResponse;

type DeleteChunkTopicData = experimental_Documents.DeleteChunkTopicData;

type CreateChunkTopicError = experimental_Documents.CreateChunkTopicError;

type CreateChunkTopicResponse = experimental_Documents.CreateChunkTopicResponse;

type CreateChunkTopicData = experimental_Documents.CreateChunkTopicData;

type ListChunkTopicsError = experimental_Documents.ListChunkTopicsError;

type ListChunkTopicsResponse = experimental_Documents.ListChunkTopicsResponse;

type ListChunkTopicsData = experimental_Documents.ListChunkTopicsData;

type GetChunkReferenceError = experimental_Documents.GetChunkReferenceError;

type GetChunkReferenceResponse = experimental_Documents.GetChunkReferenceResponse;

type GetChunkReferenceData = experimental_Documents.GetChunkReferenceData;

type DeleteChunkReferenceError = experimental_Documents.DeleteChunkReferenceError;

type DeleteChunkReferenceResponse = experimental_Documents.DeleteChunkReferenceResponse;

type DeleteChunkReferenceData = experimental_Documents.DeleteChunkReferenceData;

type CreateChunkReferenceError = experimental_Documents.CreateChunkReferenceError;

type CreateChunkReferenceResponse = experimental_Documents.CreateChunkReferenceResponse;

type CreateChunkReferenceData = experimental_Documents.CreateChunkReferenceData;

type ListChunkReferencesError = experimental_Documents.ListChunkReferencesError;

type ListChunkReferencesResponse = experimental_Documents.ListChunkReferencesResponse;

type ListChunkReferencesData = experimental_Documents.ListChunkReferencesData;

type UpdateChunkV2Error = experimental_Documents.UpdateChunkV2Error;

type UpdateChunkV2Response = experimental_Documents.UpdateChunkV2Response;

type UpdateChunkV2Data = experimental_Documents.UpdateChunkV2Data;

type GetChunkV2Error = experimental_Documents.GetChunkV2Error;

type GetChunkV2Response = experimental_Documents.GetChunkV2Response;

type GetChunkV2Data = experimental_Documents.GetChunkV2Data;

type UpdateChunkError = experimental_Documents.UpdateChunkError;

type UpdateChunkResponse = experimental_Documents.UpdateChunkResponse;

type UpdateChunkData = experimental_Documents.UpdateChunkData;

type GetChunkError = experimental_Documents.GetChunkError;

type GetChunkResponse = experimental_Documents.GetChunkResponse;

type GetChunkData = experimental_Documents.GetChunkData;

type DeleteChunkError = experimental_Documents.DeleteChunkError;

type DeleteChunkResponse = experimental_Documents.DeleteChunkResponse;

type DeleteChunkData = experimental_Documents.DeleteChunkData;

type CreateChunkV2Error = experimental_Documents.CreateChunkV2Error;

type CreateChunkV2Response = experimental_Documents.CreateChunkV2Response;

type CreateChunkV2Data = experimental_Documents.CreateChunkV2Data;

type ListChunksV2Error = experimental_Documents.ListChunksV2Error;

type ListChunksV2Response = experimental_Documents.ListChunksV2Response;

type ListChunksV2Data = experimental_Documents.ListChunksV2Data;

type CreateChunkError = experimental_Documents.CreateChunkError;

type CreateChunkResponse = experimental_Documents.CreateChunkResponse;

type CreateChunkData = experimental_Documents.CreateChunkData;

type ListChunksError = experimental_Documents.ListChunksError;

type ListChunksResponse = experimental_Documents.ListChunksResponse;

type ListChunksData = experimental_Documents.ListChunksData;

type UpdateDocumentTopicError = experimental_Documents.UpdateDocumentTopicError;

type UpdateDocumentTopicResponse = experimental_Documents.UpdateDocumentTopicResponse;

type UpdateDocumentTopicData = experimental_Documents.UpdateDocumentTopicData;

type GetDocumentTopicError = experimental_Documents.GetDocumentTopicError;

type GetDocumentTopicResponse = experimental_Documents.GetDocumentTopicResponse;

type GetDocumentTopicData = experimental_Documents.GetDocumentTopicData;

type DeleteDocumentTopicError = experimental_Documents.DeleteDocumentTopicError;

type DeleteDocumentTopicResponse = experimental_Documents.DeleteDocumentTopicResponse;

type DeleteDocumentTopicData = experimental_Documents.DeleteDocumentTopicData;

type CreateDocumentTopicError = experimental_Documents.CreateDocumentTopicError;

type CreateDocumentTopicResponse = experimental_Documents.CreateDocumentTopicResponse;

type CreateDocumentTopicData = experimental_Documents.CreateDocumentTopicData;

type ListDocumentTopicsError = experimental_Documents.ListDocumentTopicsError;

type ListDocumentTopicsResponse = experimental_Documents.ListDocumentTopicsResponse;

type ListDocumentTopicsData = experimental_Documents.ListDocumentTopicsData;

type GetDocumentReferenceError = experimental_Documents.GetDocumentReferenceError;

type GetDocumentReferenceResponse = experimental_Documents.GetDocumentReferenceResponse;

type GetDocumentReferenceData = experimental_Documents.GetDocumentReferenceData;

type DeleteDocumentReferenceError = experimental_Documents.DeleteDocumentReferenceError;

type DeleteDocumentReferenceResponse = experimental_Documents.DeleteDocumentReferenceResponse;

type DeleteDocumentReferenceData = experimental_Documents.DeleteDocumentReferenceData;

type CreateDocumentReferenceError = experimental_Documents.CreateDocumentReferenceError;

type CreateDocumentReferenceResponse = experimental_Documents.CreateDocumentReferenceResponse;

type CreateDocumentReferenceData = experimental_Documents.CreateDocumentReferenceData;

type ListDocumentReferencesError = experimental_Documents.ListDocumentReferencesError;

type ListDocumentReferencesResponse = experimental_Documents.ListDocumentReferencesResponse;

type ListDocumentReferencesData = experimental_Documents.ListDocumentReferencesData;

type UpdateDocumentV2Error = experimental_Documents.UpdateDocumentV2Error;

type UpdateDocumentV2Response = experimental_Documents.UpdateDocumentV2Response;

type UpdateDocumentV2Data = experimental_Documents.UpdateDocumentV2Data;

type GetDocumentV2Error = experimental_Documents.GetDocumentV2Error;

type GetDocumentV2Response = experimental_Documents.GetDocumentV2Response;

type GetDocumentV2Data = experimental_Documents.GetDocumentV2Data;

type UpdateDocumentError = experimental_Documents.UpdateDocumentError;

type UpdateDocumentResponse = experimental_Documents.UpdateDocumentResponse;

type UpdateDocumentData = experimental_Documents.UpdateDocumentData;

type GetDocumentError = experimental_Documents.GetDocumentError;

type GetDocumentResponse = experimental_Documents.GetDocumentResponse;

type GetDocumentData = experimental_Documents.GetDocumentData;

type DeleteDocumentError = experimental_Documents.DeleteDocumentError;

type DeleteDocumentResponse = experimental_Documents.DeleteDocumentResponse;

type DeleteDocumentData = experimental_Documents.DeleteDocumentData;

type CreateDocumentV2Error = experimental_Documents.CreateDocumentV2Error;

type CreateDocumentV2Response = experimental_Documents.CreateDocumentV2Response;

type CreateDocumentV2Data = experimental_Documents.CreateDocumentV2Data;

type ListDocumentsV2Error = experimental_Documents.ListDocumentsV2Error;

type ListDocumentsV2Response = experimental_Documents.ListDocumentsV2Response;

type ListDocumentsV2Data = experimental_Documents.ListDocumentsV2Data;

type CreateDocumentError = experimental_Documents.CreateDocumentError;

type CreateDocumentResponse = experimental_Documents.CreateDocumentResponse;

type CreateDocumentData = experimental_Documents.CreateDocumentData;

type ListDocumentsError = experimental_Documents.ListDocumentsError;

type ListDocumentsResponse = experimental_Documents.ListDocumentsResponse;

type ListDocumentsData = experimental_Documents.ListDocumentsData;

type GetVersionData = experimental_Documents.GetVersionData;

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get Version
 */
export const getVersion = <ThrowOnError extends boolean = false>(
  options?: Options<GetVersionData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
    url: '/api/version',
    ...options,
  });
};

/**
 * @deprecated
 * List Documents
 */
export const listDocuments = <ThrowOnError extends boolean = false>(
  options: Options<ListDocumentsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListDocumentsResponse,
    ListDocumentsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/documents',
    ...options,
  });
};

/**
 * @deprecated
 * Create Document
 */
export const createDocument = <ThrowOnError extends boolean = false>(
  options: Options<CreateDocumentData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateDocumentResponse,
    CreateDocumentError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/documents',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * List Documents V2
 */
export const listDocumentsV2 = <ThrowOnError extends boolean = false>(
  options: Options<ListDocumentsV2Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListDocumentsV2Response,
    ListDocumentsV2Error,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v2/organizations/{organizationId}/documents',
    ...options,
  });
};

/**
 * Create Document V2
 */
export const createDocumentV2 = <ThrowOnError extends boolean = false>(
  options: Options<CreateDocumentV2Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateDocumentV2Response,
    CreateDocumentV2Error,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v2/organizations/{organizationId}/documents',
    ...options,
    headers: {
      'Content-Type': null,
      ...options?.headers,
    },
  });
};

/**
 * Delete Document
 */
export const deleteDocument = <ThrowOnError extends boolean = false>(
  options: Options<DeleteDocumentData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteDocumentResponse,
    DeleteDocumentError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/documents/{documentId}',
    ...options,
  });
};

/**
 * @deprecated
 * Get Document
 */
export const getDocument = <ThrowOnError extends boolean = false>(
  options: Options<GetDocumentData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetDocumentResponse, GetDocumentError, ThrowOnError>(
    {
      security: [
        {
          scheme: 'bearer',
          type: 'http',
        },
      ],
      url: '/api/documents/v1/organizations/{organizationId}/documents/{documentId}',
      ...options,
    },
  );
};

/**
 * @deprecated
 * Update Document
 */
export const updateDocument = <ThrowOnError extends boolean = false>(
  options: Options<UpdateDocumentData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateDocumentResponse,
    UpdateDocumentError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/documents/{documentId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Get Document V2
 */
export const getDocumentV2 = <ThrowOnError extends boolean = false>(
  options: Options<GetDocumentV2Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetDocumentV2Response,
    GetDocumentV2Error,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v2/organizations/{organizationId}/documents/{documentId}',
    ...options,
  });
};

/**
 * Update Document V2
 */
export const updateDocumentV2 = <ThrowOnError extends boolean = false>(
  options: Options<UpdateDocumentV2Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateDocumentV2Response,
    UpdateDocumentV2Error,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v2/organizations/{organizationId}/documents/{documentId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * List Document References
 */
export const listDocumentReferences = <ThrowOnError extends boolean = false>(
  options: Options<ListDocumentReferencesData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListDocumentReferencesResponse,
    ListDocumentReferencesError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/documents/{documentId}/references',
    ...options,
  });
};

/**
 * Create Document Reference
 */
export const createDocumentReference = <ThrowOnError extends boolean = false>(
  options: Options<CreateDocumentReferenceData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateDocumentReferenceResponse,
    CreateDocumentReferenceError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/documents/{documentId}/references',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete Document Reference
 */
export const deleteDocumentReference = <ThrowOnError extends boolean = false>(
  options: Options<DeleteDocumentReferenceData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteDocumentReferenceResponse,
    DeleteDocumentReferenceError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/documents/{documentId}/references/{referenceId}',
    ...options,
  });
};

/**
 * Get Document Reference
 */
export const getDocumentReference = <ThrowOnError extends boolean = false>(
  options: Options<GetDocumentReferenceData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetDocumentReferenceResponse,
    GetDocumentReferenceError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/documents/{documentId}/references/{referenceId}',
    ...options,
  });
};

/**
 * List Document Topics
 */
export const listDocumentTopics = <ThrowOnError extends boolean = false>(
  options: Options<ListDocumentTopicsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListDocumentTopicsResponse,
    ListDocumentTopicsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/documents/{documentId}/topics',
    ...options,
  });
};

/**
 * Create Document Topic
 */
export const createDocumentTopic = <ThrowOnError extends boolean = false>(
  options: Options<CreateDocumentTopicData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateDocumentTopicResponse,
    CreateDocumentTopicError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/documents/{documentId}/topics',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete Document Topic
 */
export const deleteDocumentTopic = <ThrowOnError extends boolean = false>(
  options: Options<DeleteDocumentTopicData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteDocumentTopicResponse,
    DeleteDocumentTopicError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/documents/{documentId}/topics/{topicId}',
    ...options,
  });
};

/**
 * Get Document Topic
 */
export const getDocumentTopic = <ThrowOnError extends boolean = false>(
  options: Options<GetDocumentTopicData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetDocumentTopicResponse,
    GetDocumentTopicError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/documents/{documentId}/topics/{topicId}',
    ...options,
  });
};

/**
 * Update Document Topic
 */
export const updateDocumentTopic = <ThrowOnError extends boolean = false>(
  options: Options<UpdateDocumentTopicData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateDocumentTopicResponse,
    UpdateDocumentTopicError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/documents/{documentId}/topics/{topicId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * @deprecated
 * List Chunks
 */
export const listChunks = <ThrowOnError extends boolean = false>(
  options: Options<ListChunksData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<ListChunksResponse, ListChunksError, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/chunks',
    ...options,
  });
};

/**
 * @deprecated
 * Create Chunk
 */
export const createChunk = <ThrowOnError extends boolean = false>(
  options: Options<CreateChunkData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateChunkResponse,
    CreateChunkError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/chunks',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * List Chunks V2
 */
export const listChunksV2 = <ThrowOnError extends boolean = false>(
  options: Options<ListChunksV2Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListChunksV2Response,
    ListChunksV2Error,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v2/organizations/{organizationId}/chunks',
    ...options,
  });
};

/**
 * Create Chunk V2
 */
export const createChunkV2 = <ThrowOnError extends boolean = false>(
  options: Options<CreateChunkV2Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateChunkV2Response,
    CreateChunkV2Error,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v2/organizations/{organizationId}/chunks',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete Chunk
 */
export const deleteChunk = <ThrowOnError extends boolean = false>(
  options: Options<DeleteChunkData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteChunkResponse,
    DeleteChunkError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/chunks/{chunkId}',
    ...options,
  });
};

/**
 * @deprecated
 * Get Chunk
 */
export const getChunk = <ThrowOnError extends boolean = false>(
  options: Options<GetChunkData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetChunkResponse, GetChunkError, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/chunks/{chunkId}',
    ...options,
  });
};

/**
 * @deprecated
 * Update Chunk
 */
export const updateChunk = <ThrowOnError extends boolean = false>(
  options: Options<UpdateChunkData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateChunkResponse,
    UpdateChunkError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/chunks/{chunkId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Get Chunk V2
 */
export const getChunkV2 = <ThrowOnError extends boolean = false>(
  options: Options<GetChunkV2Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetChunkV2Response, GetChunkV2Error, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v2/organizations/{organizationId}/chunks/{chunkId}',
    ...options,
  });
};

/**
 * Update Chunk V2
 */
export const updateChunkV2 = <ThrowOnError extends boolean = false>(
  options: Options<UpdateChunkV2Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateChunkV2Response,
    UpdateChunkV2Error,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v2/organizations/{organizationId}/chunks/{chunkId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * List Chunk References
 */
export const listChunkReferences = <ThrowOnError extends boolean = false>(
  options: Options<ListChunkReferencesData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListChunkReferencesResponse,
    ListChunkReferencesError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/chunks/{chunkId}/references',
    ...options,
  });
};

/**
 * Create Chunk Reference
 */
export const createChunkReference = <ThrowOnError extends boolean = false>(
  options: Options<CreateChunkReferenceData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateChunkReferenceResponse,
    CreateChunkReferenceError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/chunks/{chunkId}/references',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete Chunk Reference
 */
export const deleteChunkReference = <ThrowOnError extends boolean = false>(
  options: Options<DeleteChunkReferenceData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteChunkReferenceResponse,
    DeleteChunkReferenceError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/chunks/{chunkId}/references/{referenceId}',
    ...options,
  });
};

/**
 * Get Chunk Reference
 */
export const getChunkReference = <ThrowOnError extends boolean = false>(
  options: Options<GetChunkReferenceData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetChunkReferenceResponse,
    GetChunkReferenceError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/chunks/{chunkId}/references/{referenceId}',
    ...options,
  });
};

/**
 * List Chunk Topics
 */
export const listChunkTopics = <ThrowOnError extends boolean = false>(
  options: Options<ListChunkTopicsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListChunkTopicsResponse,
    ListChunkTopicsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/chunks/{chunkId}/topics',
    ...options,
  });
};

/**
 * Create Chunk Topic
 */
export const createChunkTopic = <ThrowOnError extends boolean = false>(
  options: Options<CreateChunkTopicData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateChunkTopicResponse,
    CreateChunkTopicError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/chunks/{chunkId}/topics',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * Delete Chunk Topic
 */
export const deleteChunkTopic = <ThrowOnError extends boolean = false>(
  options: Options<DeleteChunkTopicData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteChunkTopicResponse,
    DeleteChunkTopicError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/chunks/{chunkId}/topics/{topicId}',
    ...options,
  });
};

/**
 * Get Chunk Topic
 */
export const getChunkTopic = <ThrowOnError extends boolean = false>(
  options: Options<GetChunkTopicData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetChunkTopicResponse,
    GetChunkTopicError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/chunks/{chunkId}/topics/{topicId}',
    ...options,
  });
};

/**
 * Update Chunk Topic
 */
export const updateChunkTopic = <ThrowOnError extends boolean = false>(
  options: Options<UpdateChunkTopicData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateChunkTopicResponse,
    UpdateChunkTopicError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/chunks/{chunkId}/topics/{topicId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * @deprecated
 * List Chunk Fields
 */
export const listChunkFields = <ThrowOnError extends boolean = false>(
  options: Options<ListChunkFieldsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListChunkFieldsResponse,
    ListChunkFieldsError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/chunks/{chunkId}/fields',
    ...options,
  });
};

/**
 * @deprecated
 * Create Chunk Field
 */
export const createChunkField = <ThrowOnError extends boolean = false>(
  options: Options<CreateChunkFieldData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateChunkFieldResponse,
    CreateChunkFieldError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/chunks/{chunkId}/fields',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

/**
 * @deprecated
 * Delete Chunk Field
 */
export const deleteChunkField = <ThrowOnError extends boolean = false>(
  options: Options<DeleteChunkFieldData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteChunkFieldResponse,
    DeleteChunkFieldError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/chunks/{chunkId}/fields/{fieldId}',
    ...options,
  });
};

/**
 * @deprecated
 * Get Chunk Field
 */
export const getChunkField = <ThrowOnError extends boolean = false>(
  options: Options<GetChunkFieldData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetChunkFieldResponse,
    GetChunkFieldError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v1/organizations/{organizationId}/chunks/{chunkId}/fields/{fieldId}',
    ...options,
  });
};

/**
 * Get Chunk File V2
 */
export const getChunkFileV2 = <ThrowOnError extends boolean = false>(
  options: Options<GetChunkFileV2Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<unknown, GetChunkFileV2Error, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v2/chunk/file/{fileId}',
    ...options,
  });
};

/**
 * Get File V2
 */
export const getFileV2 = <ThrowOnError extends boolean = false>(
  options: Options<GetFileV2Data, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<unknown, GetFileV2Error, ThrowOnError>({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/v2/file/{fileId}',
    ...options,
  });
};

/**
 * List Chunks Admin
 */
export const listChunksAdmin = <ThrowOnError extends boolean = false>(
  options: Options<ListChunksAdminData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListChunksAdminResponse,
    ListChunksAdminError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/documents/admin/v1/chunks',
    ...options,
  });
};

/**
 * Get Public Openapi
 * Generate public OpenAPI documentation that only includes routes tagged as 'public'.
 */
export const getPublicOpenapi = <ThrowOnError extends boolean = false>(
  options?: Options<GetPublicOpenapiData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
    url: '/api/docs/openapi.json',
    ...options,
  });
};

/**
 * Get Public Swagger Ui
 * Generate Swagger UI HTML page for public OpenAPI documentation.
 */
export const getPublicSwaggerUi = <ThrowOnError extends boolean = false>(
  options?: Options<GetPublicSwaggerUiData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetPublicSwaggerUiResponse, unknown, ThrowOnError>({
    url: '/api/docs',
    ...options,
  });
};

/**
 * Get Public Redoc Ui
 * Generate ReDoc HTML page for public OpenAPI documentation.
 */
export const getPublicRedocUi = <ThrowOnError extends boolean = false>(
  options?: Options<GetPublicRedocUiData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetPublicRedocUiResponse, unknown, ThrowOnError>({
    url: '/api/docs/redoc',
    ...options,
  });
};
