// This file is auto-generated by @hey-api/openapi-ts

export namespace Search {
  export type Config = {
    contentType?: string;
    contentTypes?: Array<string>;
    context?: {
      [key: string]: string;
    };
    createdAt?: string;
    createdBy?: string;
    description?: string;
    fields?: Array<Field>;
    id?: string;
    name?: string;
    searchClientKey?: string;
    searchSettings?: SearchSettings;
    templateId?: string;
    templateIds?: Array<string>;
    tenantId?: string;
    updatedAt?: string;
    updatedBy?: string;
  };
  export type ErrorResponse = {
    code?: number;
    internal?: {
      [key: string]: unknown;
    };
    message?: {
      [key: string]: unknown;
    };
  };
  export type Field = {
    description?: string;
    displayName?: string;
    facet?: SearchFeature;
    filter?: SearchFeature;
    id?: string;
    key?: SearchFeature;
    name?: string;
    retrieve?: SearchFeature;
    search?: SearchFeature;
    sort?: SearchFeature;
    type?: string;
  };
  export type SearchFeature = {
    enabled?: boolean;
    name?: string;
  };
  export type SearchSettings = {
    fuzzySearch?: SearchFeature;
  };
  export type GetConfigsData = {
    body?: never;
    path?: never;
    query?: {
      /**
       * Context filters
       */
      'context.*'?: string;
      /**
       * The Sitecore context ID.
       */
      sitecoreContextId?: string;
    };
    url: '/v1/config';
  };
  export type GetConfigsErrors = {
    /**
     * Auth error
     */
    400: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
  };
  export type GetConfigsError = GetConfigsErrors[keyof GetConfigsErrors];
  export type GetConfigsResponses = {
    /**
     * Success response
     */
    200: Array<Config>;
  };
  export type GetConfigsResponse = GetConfigsResponses[keyof GetConfigsResponses];
  export type ClientOptions = {
    baseUrl: 'https://edge-platform.sitecorecloud.io/search' | (string & {});
  };
}
