name: on-push-pull-request

on:
  pull_request:
    branches: [master]

jobs:
  unit-test:
    uses: ./.github/workflows/unit-test.yaml
    secrets: inherit

  pnpm-dependencies-scan:
    uses: ./.github/workflows/pnpm-dependencies-scan.yaml
